//
// AccountPaymentModesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class AccountPaymentModesAPI {

    /**
     Add payment mode to account
     
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter accountPaymentModeRequest: (body) The AccountPaymentModeRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: AccountPaymentModeResponse
     */
    open class func createAccountPaymentMode(xKarageRequestId: String, xAccountID: Int, xLocationID: Int, accountPaymentModeRequest: AccountPaymentModeRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> AccountPaymentModeResponse {
        return try await createAccountPaymentModeWithRequestBuilder(xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, accountPaymentModeRequest: accountPaymentModeRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Add payment mode to account
     - POST /api/v1/account-payment-modes
     - Associates a payment mode with an account. The account is identified from the authentication context.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter accountPaymentModeRequest: (body) The AccountPaymentModeRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<AccountPaymentModeResponse> 
     */
    open class func createAccountPaymentModeWithRequestBuilder(xKarageRequestId: String, xAccountID: Int, xLocationID: Int, accountPaymentModeRequest: AccountPaymentModeRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<AccountPaymentModeResponse> {
        let localVariablePath = "/api/v1/account-payment-modes"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: accountPaymentModeRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AccountPaymentModeResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete account payment mode
     
     - parameter accountPaymentModeID: (path) The unique identifier of the account payment mode association to delete 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteAccountPaymentMode(accountPaymentModeID: Int64, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteAccountPaymentModeWithRequestBuilder(accountPaymentModeID: accountPaymentModeID, xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete account payment mode
     - DELETE /api/v1/account-payment-modes/{AccountPaymentModeID}
     - Removes the association between an account and a payment mode. This does not delete the payment mode itself, only the link between the account and the payment mode.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter accountPaymentModeID: (path) The unique identifier of the account payment mode association to delete 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteAccountPaymentModeWithRequestBuilder(accountPaymentModeID: Int64, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/account-payment-modes/{AccountPaymentModeID}"
        let accountPaymentModeIDPreEscape = "\(APIHelper.mapValueToPathItem(accountPaymentModeID))"
        let accountPaymentModeIDPostEscape = accountPaymentModeIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{AccountPaymentModeID}", with: accountPaymentModeIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get account payment mode by ID
     
     - parameter accountPaymentModeID: (path) The unique identifier of the account payment mode association 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: AccountPaymentModeResponse
     */
    open class func getAccountPaymentModeById(accountPaymentModeID: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> AccountPaymentModeResponse {
        return try await getAccountPaymentModeByIdWithRequestBuilder(accountPaymentModeID: accountPaymentModeID, xAccountID: xAccountID, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get account payment mode by ID
     - GET /api/v1/account-payment-modes/{AccountPaymentModeID}
     - Retrieves detailed information about a specific account payment mode association, including the related payment mode details.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter accountPaymentModeID: (path) The unique identifier of the account payment mode association 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<AccountPaymentModeResponse> 
     */
    open class func getAccountPaymentModeByIdWithRequestBuilder(accountPaymentModeID: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<AccountPaymentModeResponse> {
        var localVariablePath = "/api/v1/account-payment-modes/{AccountPaymentModeID}"
        let accountPaymentModeIDPreEscape = "\(APIHelper.mapValueToPathItem(accountPaymentModeID))"
        let accountPaymentModeIDPostEscape = accountPaymentModeIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{AccountPaymentModeID}", with: accountPaymentModeIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AccountPaymentModeResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get all account payment modes with filtering
     
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter filters: (query) The Filters query parameter (optional)
     - parameter page: (query) Page number for pagination (1-based) (optional)
     - parameter pageSize: (query) Number of items per page (optional)
     - parameter sortBy: (query) Field name to sort by (optional)
     - parameter sortDirection: (query) The SortDirection query parameter (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PagedResultOfAccountPaymentModeResponse
     */
    open class func getAccountPaymentModes(xAccountID: Int, xLocationID: Int, filters: String? = nil, page: Int? = nil, pageSize: Int? = nil, sortBy: String? = nil, sortDirection: String? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> PagedResultOfAccountPaymentModeResponse {
        return try await getAccountPaymentModesWithRequestBuilder(xAccountID: xAccountID, xLocationID: xLocationID, filters: filters, page: page, pageSize: pageSize, sortBy: sortBy, sortDirection: sortDirection, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get all account payment modes with filtering
     - GET /api/v1/account-payment-modes
     - Retrieves a paginated list of account payment mode associations with advanced filtering and sorting capabilities.  **Query Parameters:** - **page**: Page number (default: 1) - **pageSize**: Items per page (default: 10, max: 100) - **sortBy**: Field name to sort by (default: AccountPaymentModeID) - **sortDirection**: Sort direction - 'asc' or 'desc' (default: asc) - **filters**: JSON array of FilterRule objects for complex filtering  **Supported Filter Fields:** - AccountPaymentModeID, AccountID, PaymentModeID - CreatedAt, UpdatedAt  **Filter Operators:** - eq (equals), ne (not equals) - gt (greater than), gte (greater than or equal) - lt (less than), lte (less than or equal) - contains, startswith, endswith - in (value in list) - between (requires two values for dates/numbers)
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter filters: (query) The Filters query parameter (optional)
     - parameter page: (query) Page number for pagination (1-based) (optional)
     - parameter pageSize: (query) Number of items per page (optional)
     - parameter sortBy: (query) Field name to sort by (optional)
     - parameter sortDirection: (query) The SortDirection query parameter (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PagedResultOfAccountPaymentModeResponse> 
     */
    open class func getAccountPaymentModesWithRequestBuilder(xAccountID: Int, xLocationID: Int, filters: String? = nil, page: Int? = nil, pageSize: Int? = nil, sortBy: String? = nil, sortDirection: String? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<PagedResultOfAccountPaymentModeResponse> {
        let localVariablePath = "/api/v1/account-payment-modes"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "Filters": (wrappedValue: filters?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "Page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "PageSize": (wrappedValue: pageSize?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "SortBy": (wrappedValue: sortBy?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "SortDirection": (wrappedValue: sortDirection?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PagedResultOfAccountPaymentModeResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update account payment mode
     
     - parameter accountPaymentModeID: (path) The unique identifier of the account payment mode association to update 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter accountPaymentModeRequest: (body) The AccountPaymentModeRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: AccountPaymentModeResponse
     */
    open class func updateAccountPaymentMode(accountPaymentModeID: String, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, accountPaymentModeRequest: AccountPaymentModeRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> AccountPaymentModeResponse {
        return try await updateAccountPaymentModeWithRequestBuilder(accountPaymentModeID: accountPaymentModeID, xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, accountPaymentModeRequest: accountPaymentModeRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update account payment mode
     - PUT /api/v1/account-payment-modes/{AccountPaymentModeID}
     - Updates the payment mode associated with an account payment mode record. Only the PaymentModeID can be changed.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter accountPaymentModeID: (path) The unique identifier of the account payment mode association to update 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter accountPaymentModeRequest: (body) The AccountPaymentModeRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<AccountPaymentModeResponse> 
     */
    open class func updateAccountPaymentModeWithRequestBuilder(accountPaymentModeID: String, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, accountPaymentModeRequest: AccountPaymentModeRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<AccountPaymentModeResponse> {
        var localVariablePath = "/api/v1/account-payment-modes/{AccountPaymentModeID}"
        let accountPaymentModeIDPreEscape = "\(APIHelper.mapValueToPathItem(accountPaymentModeID))"
        let accountPaymentModeIDPostEscape = accountPaymentModeIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{AccountPaymentModeID}", with: accountPaymentModeIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: accountPaymentModeRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AccountPaymentModeResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
