//
// AppSourcesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class AppSourcesAPI {

    /**
     Create a new app source
     
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter appSourceRequest: (body) The AppSourceRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: AppSourceResponse
     */
    open class func createAppSource(xKarageRequestId: String, xAccountID: Int, xLocationID: Int, appSourceRequest: AppSourceRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> AppSourceResponse {
        return try await createAppSourceWithRequestBuilder(xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, appSourceRequest: appSourceRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create a new app source
     - POST /api/v1/appsources
     - Create a new app source with the specified details
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter appSourceRequest: (body) The AppSourceRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<AppSourceResponse> 
     */
    open class func createAppSourceWithRequestBuilder(xKarageRequestId: String, xAccountID: Int, xLocationID: Int, appSourceRequest: AppSourceRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<AppSourceResponse> {
        let localVariablePath = "/api/v1/appsources"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: appSourceRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AppSourceResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete an app source
     
     - parameter appSourceID: (path) The unique identifier of the appsource 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteAppSource(appSourceID: Int64, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteAppSourceWithRequestBuilder(appSourceID: appSourceID, xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete an app source
     - DELETE /api/v1/appsources/{AppSourceID}
     - Delete an app source by its ID
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter appSourceID: (path) The unique identifier of the appsource 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteAppSourceWithRequestBuilder(appSourceID: Int64, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/appsources/{AppSourceID}"
        let appSourceIDPreEscape = "\(APIHelper.mapValueToPathItem(appSourceID))"
        let appSourceIDPostEscape = appSourceIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{AppSourceID}", with: appSourceIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get a specific app source by ID
     
     - parameter appSourceID: (path) The unique identifier of the appsource 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: AppSourceResponse
     */
    open class func getAppSourceById(appSourceID: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> AppSourceResponse {
        return try await getAppSourceByIdWithRequestBuilder(appSourceID: appSourceID, xAccountID: xAccountID, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a specific app source by ID
     - GET /api/v1/appsources/{AppSourceID}
     - Retrieve a single app source using its ID
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter appSourceID: (path) The unique identifier of the appsource 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<AppSourceResponse> 
     */
    open class func getAppSourceByIdWithRequestBuilder(appSourceID: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<AppSourceResponse> {
        var localVariablePath = "/api/v1/appsources/{AppSourceID}"
        let appSourceIDPreEscape = "\(APIHelper.mapValueToPathItem(appSourceID))"
        let appSourceIDPostEscape = appSourceIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{AppSourceID}", with: appSourceIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AppSourceResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get app sources with dynamic filtering, pagination, and sorting
     
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter filters: (query) The Filters query parameter (optional)
     - parameter page: (query) Page number for pagination (1-based) (optional)
     - parameter pageSize: (query) Number of items per page (optional)
     - parameter sortBy: (query) Field name to sort by (optional)
     - parameter sortDirection: (query) The SortDirection query parameter (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PagedResultOfAppSourceResponse
     */
    open class func getAppSources(xAccountID: Int, xLocationID: Int, filters: String? = nil, page: Int? = nil, pageSize: Int? = nil, sortBy: String? = nil, sortDirection: String? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> PagedResultOfAppSourceResponse {
        return try await getAppSourcesWithRequestBuilder(xAccountID: xAccountID, xLocationID: xLocationID, filters: filters, page: page, pageSize: pageSize, sortBy: sortBy, sortDirection: sortDirection, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get app sources with dynamic filtering, pagination, and sorting
     - GET /api/v1/appsources
     -  Supports dynamic filtering, pagination, and sorting using the same FilterRule structure as the POST endpoint.  For complex filtering, you can pass filters as JSON in query parameters: GET /api/v1/appsources?filters=[{\"Field\":\"Name\",\"Operator\":\"contains\",\"Values\":[\"Mobile\"]}]  Available parameters: - page: Page number (default: 1) - pageSize: Items per page (default: 10, max: 100) - sortBy: Field name to sort by (default: UpdatedAt) - sortDirection: 'asc' or 'desc' (default: desc) - filters: JSON array of FilterRule objects  FilterRule structure: - Field: Property name to filter on (e.g., 'Name', 'NameAr', 'AppSourceID') - Operator: Filter operator - 'eq', 'neq', 'gt', 'lt', 'gte', 'lte', 'contains', 'between' - Values: Array of values for the filter  This endpoint uses the same QueryFilterExtensions.ApplyDynamicFilters and ApplySorting methods as the POST endpoint for complete consistency. 
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter filters: (query) The Filters query parameter (optional)
     - parameter page: (query) Page number for pagination (1-based) (optional)
     - parameter pageSize: (query) Number of items per page (optional)
     - parameter sortBy: (query) Field name to sort by (optional)
     - parameter sortDirection: (query) The SortDirection query parameter (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PagedResultOfAppSourceResponse> 
     */
    open class func getAppSourcesWithRequestBuilder(xAccountID: Int, xLocationID: Int, filters: String? = nil, page: Int? = nil, pageSize: Int? = nil, sortBy: String? = nil, sortDirection: String? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<PagedResultOfAppSourceResponse> {
        let localVariablePath = "/api/v1/appsources"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "Filters": (wrappedValue: filters?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "Page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "PageSize": (wrappedValue: pageSize?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "SortBy": (wrappedValue: sortBy?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "SortDirection": (wrappedValue: sortDirection?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PagedResultOfAppSourceResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update an existing app source
     
     - parameter appSourceID: (path) The unique identifier of the appsource 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter appSourceRequest: (body) The AppSourceRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: AppSourceResponse
     */
    open class func updateAppSource(appSourceID: String, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, appSourceRequest: AppSourceRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> AppSourceResponse {
        return try await updateAppSourceWithRequestBuilder(appSourceID: appSourceID, xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, appSourceRequest: appSourceRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update an existing app source
     - PUT /api/v1/appsources/{AppSourceID}
     - Update an app source with the specified details. Only provided fields will be updated.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter appSourceID: (path) The unique identifier of the appsource 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter appSourceRequest: (body) The AppSourceRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<AppSourceResponse> 
     */
    open class func updateAppSourceWithRequestBuilder(appSourceID: String, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, appSourceRequest: AppSourceRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<AppSourceResponse> {
        var localVariablePath = "/api/v1/appsources/{AppSourceID}"
        let appSourceIDPreEscape = "\(APIHelper.mapValueToPathItem(appSourceID))"
        let appSourceIDPostEscape = appSourceIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{AppSourceID}", with: appSourceIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: appSourceRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AppSourceResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
