//
// CarsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class CarsAPI {

    /**
     Create a new car
     
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter carRequest: (body) The CarRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CarResponse
     */
    open class func createCar(xKarageRequestId: String, xAccountID: Int, xLocationID: Int, carRequest: CarRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> CarResponse {
        return try await createCarWithRequestBuilder(xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, carRequest: carRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create a new car
     - POST /api/v1/cars
     - Creates a new car with the following requirements: 
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter carRequest: (body) The CarRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CarResponse> 
     */
    open class func createCarWithRequestBuilder(xKarageRequestId: String, xAccountID: Int, xLocationID: Int, carRequest: CarRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<CarResponse> {
        let localVariablePath = "/api/v1/cars"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: carRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CarResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete a car
     
     - parameter carID: (path) The unique identifier of the car 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteCar(carID: Int64, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteCarWithRequestBuilder(carID: carID, xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete a car
     - DELETE /api/v1/cars/{CarID}
     - Deletes a car by CarID. Responds with 204 no-content if successful, 404 if not found.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter carID: (path) The unique identifier of the car 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteCarWithRequestBuilder(carID: Int64, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/cars/{CarID}"
        let carIDPreEscape = "\(APIHelper.mapValueToPathItem(carID))"
        let carIDPostEscape = carIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{CarID}", with: carIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get a single car by ID
     
     - parameter carID: (path) The unique identifier of the car 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CarResponse
     */
    open class func getCarById(carID: Int64, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> CarResponse {
        return try await getCarByIdWithRequestBuilder(carID: carID, xAccountID: xAccountID, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a single car by ID
     - GET /api/v1/cars/{CarID}
     - Retrieves a single car by its CarID, including related entities (Customer, Make, Model).
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter carID: (path) The unique identifier of the car 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CarResponse> 
     */
    open class func getCarByIdWithRequestBuilder(carID: Int64, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<CarResponse> {
        var localVariablePath = "/api/v1/cars/{CarID}"
        let carIDPreEscape = "\(APIHelper.mapValueToPathItem(carID))"
        let carIDPostEscape = carIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{CarID}", with: carIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CarResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get cars with dynamic filtering, pagination, and sorting
     
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter filters: (query) The Filters query parameter (optional)
     - parameter page: (query) Page number for pagination (1-based) (optional)
     - parameter pageSize: (query) Number of items per page (optional)
     - parameter sortBy: (query) Field name to sort by (optional)
     - parameter sortDirection: (query) The SortDirection query parameter (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PagedResultOfCarResponse
     */
    open class func getCars(xAccountID: Int, xLocationID: Int, filters: String? = nil, page: Int? = nil, pageSize: Int? = nil, sortBy: String? = nil, sortDirection: String? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> PagedResultOfCarResponse {
        return try await getCarsWithRequestBuilder(xAccountID: xAccountID, xLocationID: xLocationID, filters: filters, page: page, pageSize: pageSize, sortBy: sortBy, sortDirection: sortDirection, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get cars with dynamic filtering, pagination, and sorting
     - GET /api/v1/cars
     -  Supports dynamic filtering, pagination, and sorting using the same FilterRule structure as the other endpoints.  For complex filtering, you can pass filters as JSON in query parameters: GET /api/v1/cars?filters=[{\"Field\":\"Color\",\"Operator\":\"contains\",\"Values\":[\"Blue\"]}]  Available parameters: - page: Page number (default: 1) - pageSize: Items per page (default: 10, max: 100) - sortBy: Field name to sort by (default: UpdatedAt) - sortDirection: 'asc' or 'desc' (default: desc) - filters: JSON array of FilterRule objects  FilterRule structure: - Field: Property name to filter on (e.g., 'Description', 'VinNo', 'Color', 'RegistrationNo') - Operator: Filter operator - 'eq', 'neq', 'gt', 'lt', 'gte', 'lte', 'contains', 'between' - Values: Array of values for the filter  This endpoint uses the same QueryFilterExtensions.ApplyDynamicFilters and ApplySorting methods as the POST endpoint for complete consistency. 
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter filters: (query) The Filters query parameter (optional)
     - parameter page: (query) Page number for pagination (1-based) (optional)
     - parameter pageSize: (query) Number of items per page (optional)
     - parameter sortBy: (query) Field name to sort by (optional)
     - parameter sortDirection: (query) The SortDirection query parameter (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PagedResultOfCarResponse> 
     */
    open class func getCarsWithRequestBuilder(xAccountID: Int, xLocationID: Int, filters: String? = nil, page: Int? = nil, pageSize: Int? = nil, sortBy: String? = nil, sortDirection: String? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<PagedResultOfCarResponse> {
        let localVariablePath = "/api/v1/cars"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "Filters": (wrappedValue: filters?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "Page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "PageSize": (wrappedValue: pageSize?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "SortBy": (wrappedValue: sortBy?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "SortDirection": (wrappedValue: sortDirection?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PagedResultOfCarResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update an existing car
     
     - parameter carID: (path) The unique identifier of the car 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter carRequest: (body) The CarRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CarResponse
     */
    open class func updateCar(carID: String, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, carRequest: CarRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> CarResponse {
        return try await updateCarWithRequestBuilder(carID: carID, xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, carRequest: carRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update an existing car
     - PUT /api/v1/cars/{CarID}
     - Updates an existing car with the following validation: 
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter carID: (path) The unique identifier of the car 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter carRequest: (body) The CarRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CarResponse> 
     */
    open class func updateCarWithRequestBuilder(carID: String, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, carRequest: CarRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<CarResponse> {
        var localVariablePath = "/api/v1/cars/{CarID}"
        let carIDPreEscape = "\(APIHelper.mapValueToPathItem(carID))"
        let carIDPostEscape = carIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{CarID}", with: carIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: carRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CarResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
