//
// LocationsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class LocationsAPI {

    /**
     Create a new business location
     
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter locationRequest: (body) The LocationRequest parameter 
     - parameter xLocationID: (header) The location ID to operate under (Optional) (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: LocationResponse
     */
    open class func createLocation(xKarageRequestId: String, xAccountID: Int, locationRequest: LocationRequest, xLocationID: Int? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> LocationResponse {
        return try await createLocationWithRequestBuilder(xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, locationRequest: locationRequest, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create a new business location
     - POST /api/v1/locations
     - Creates a new business location within an account with comprehensive address and contact information.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter locationRequest: (body) The LocationRequest parameter 
     - parameter xLocationID: (header) The location ID to operate under (Optional) (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<LocationResponse> 
     */
    open class func createLocationWithRequestBuilder(xKarageRequestId: String, xAccountID: Int, locationRequest: LocationRequest, xLocationID: Int? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<LocationResponse> {
        let localVariablePath = "/api/v1/locations"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: locationRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID?.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<LocationResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete a business location
     
     - parameter locationID: (path) The unique identifier of the location 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Optional) (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteLocation(locationID: Int64, xKarageRequestId: String, xAccountID: Int, xLocationID: Int? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteLocationWithRequestBuilder(locationID: locationID, xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete a business location
     - DELETE /api/v1/locations/{LocationID}
     - Permanently deletes a business location from the system with relationship validation.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter locationID: (path) The unique identifier of the location 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Optional) (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteLocationWithRequestBuilder(locationID: Int64, xKarageRequestId: String, xAccountID: Int, xLocationID: Int? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/locations/{LocationID}"
        let locationIDPreEscape = "\(APIHelper.mapValueToPathItem(locationID))"
        let locationIDPostEscape = locationIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{LocationID}", with: locationIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID?.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get a business location by ID
     
     - parameter locationID: (path) The unique identifier of the location 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Optional) (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: LocationResponse
     */
    open class func getLocationById(locationID: String, xAccountID: Int, xLocationID: Int? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> LocationResponse {
        return try await getLocationByIdWithRequestBuilder(locationID: locationID, xAccountID: xAccountID, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a business location by ID
     - GET /api/v1/locations/{LocationID}
     - Retrieves a specific business location by its unique identifier with complete details.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter locationID: (path) The unique identifier of the location 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Optional) (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<LocationResponse> 
     */
    open class func getLocationByIdWithRequestBuilder(locationID: String, xAccountID: Int, xLocationID: Int? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<LocationResponse> {
        var localVariablePath = "/api/v1/locations/{LocationID}"
        let locationIDPreEscape = "\(APIHelper.mapValueToPathItem(locationID))"
        let locationIDPostEscape = locationIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{LocationID}", with: locationIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID?.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<LocationResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get all location settings for a specific location
     
     - parameter locationID: (path) The unique identifier of the location 
     - parameter page: (query) Page number for pagination (1-based) 
     - parameter pageSize: (query) Number of items per page 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Optional) (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: TypedLocationSettingsResponse
     */
    open class func getLocationSettingById(locationID: String, page: Int, pageSize: Int, xAccountID: Int, xLocationID: Int? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> TypedLocationSettingsResponse {
        return try await getLocationSettingByIdWithRequestBuilder(locationID: locationID, page: page, pageSize: pageSize, xAccountID: xAccountID, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get all location settings for a specific location
     - GET /api/v1/locations/{LocationID}/settings
     - Retrieves all location settings (kashier, discount, lite, hardware, receipt) for a specific location by its ID as a structured object.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter locationID: (path) The unique identifier of the location 
     - parameter page: (query) Page number for pagination (1-based) 
     - parameter pageSize: (query) Number of items per page 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Optional) (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<TypedLocationSettingsResponse> 
     */
    open class func getLocationSettingByIdWithRequestBuilder(locationID: String, page: Int, pageSize: Int, xAccountID: Int, xLocationID: Int? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<TypedLocationSettingsResponse> {
        var localVariablePath = "/api/v1/locations/{LocationID}/settings"
        let locationIDPreEscape = "\(APIHelper.mapValueToPathItem(locationID))"
        let locationIDPostEscape = locationIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{LocationID}", with: locationIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "Page": (wrappedValue: page.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "PageSize": (wrappedValue: pageSize.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID?.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<TypedLocationSettingsResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get business locations with advanced filtering and pagination
     
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter filters: (query) The Filters query parameter (optional)
     - parameter page: (query) Page number for pagination (1-based) (optional)
     - parameter pageSize: (query) Number of items per page (optional)
     - parameter sortBy: (query) Field name to sort by (optional)
     - parameter sortDirection: (query) The SortDirection query parameter (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PagedResultOfLocationResponse
     */
    open class func getLocations(xAccountID: Int, filters: String? = nil, page: Int? = nil, pageSize: Int? = nil, sortBy: String? = nil, sortDirection: String? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> PagedResultOfLocationResponse {
        return try await getLocationsWithRequestBuilder(xAccountID: xAccountID, filters: filters, page: page, pageSize: pageSize, sortBy: sortBy, sortDirection: sortDirection, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get business locations with advanced filtering and pagination
     - GET /api/v1/locations
     - Retrieves business locations with comprehensive filtering, pagination, and sorting capabilities.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter filters: (query) The Filters query parameter (optional)
     - parameter page: (query) Page number for pagination (1-based) (optional)
     - parameter pageSize: (query) Number of items per page (optional)
     - parameter sortBy: (query) Field name to sort by (optional)
     - parameter sortDirection: (query) The SortDirection query parameter (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PagedResultOfLocationResponse> 
     */
    open class func getLocationsWithRequestBuilder(xAccountID: Int, filters: String? = nil, page: Int? = nil, pageSize: Int? = nil, sortBy: String? = nil, sortDirection: String? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<PagedResultOfLocationResponse> {
        let localVariablePath = "/api/v1/locations"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "Filters": (wrappedValue: filters?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "Page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "PageSize": (wrappedValue: pageSize?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "SortBy": (wrappedValue: sortBy?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "SortDirection": (wrappedValue: sortDirection?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PagedResultOfLocationResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update an existing business location
     
     - parameter locationID: (path) The unique identifier of the location 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter locationRequest: (body) The LocationRequest parameter 
     - parameter xLocationID: (header) The location ID to operate under (Optional) (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: LocationResponse
     */
    open class func updateLocation(locationID: String, xKarageRequestId: String, xAccountID: Int, locationRequest: LocationRequest, xLocationID: Int? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> LocationResponse {
        return try await updateLocationWithRequestBuilder(locationID: locationID, xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, locationRequest: locationRequest, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update an existing business location
     - PUT /api/v1/locations/{LocationID}
     - Updates an existing business location with comprehensive information including address, contact details, and operational settings.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter locationID: (path) The unique identifier of the location 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter locationRequest: (body) The LocationRequest parameter 
     - parameter xLocationID: (header) The location ID to operate under (Optional) (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<LocationResponse> 
     */
    open class func updateLocationWithRequestBuilder(locationID: String, xKarageRequestId: String, xAccountID: Int, locationRequest: LocationRequest, xLocationID: Int? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<LocationResponse> {
        var localVariablePath = "/api/v1/locations/{LocationID}"
        let locationIDPreEscape = "\(APIHelper.mapValueToPathItem(locationID))"
        let locationIDPostEscape = locationIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{LocationID}", with: locationIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: locationRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID?.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<LocationResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
