//
// MakesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class MakesAPI {

    /**
     Create a new vehicle make
     
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter makeRequest: (body) The MakeRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MakeResponse
     */
    open class func createMake(xKarageRequestId: String, xAccountID: Int, xLocationID: Int, makeRequest: MakeRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> MakeResponse {
        return try await createMakeWithRequestBuilder(xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, makeRequest: makeRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create a new vehicle make
     - POST /api/v1/makes
     - Creates a new vehicle make (manufacturer) in the system with bilingual support.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter makeRequest: (body) The MakeRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MakeResponse> 
     */
    open class func createMakeWithRequestBuilder(xKarageRequestId: String, xAccountID: Int, xLocationID: Int, makeRequest: MakeRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<MakeResponse> {
        let localVariablePath = "/api/v1/makes"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: makeRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MakeResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete a vehicle make
     
     - parameter makeID: (path) The unique identifier of the make 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteMake(makeID: Int64, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteMakeWithRequestBuilder(makeID: makeID, xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete a vehicle make
     - DELETE /api/v1/makes/{MakeID}
     - Deletes a vehicle make from the system with comprehensive relationship validation.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter makeID: (path) The unique identifier of the make 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteMakeWithRequestBuilder(makeID: Int64, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/makes/{MakeID}"
        let makeIDPreEscape = "\(APIHelper.mapValueToPathItem(makeID))"
        let makeIDPostEscape = makeIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{MakeID}", with: makeIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get a vehicle make by ID
     
     - parameter makeID: (path) The unique identifier of the make 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MakeResponse
     */
    open class func getMakeById(makeID: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> MakeResponse {
        return try await getMakeByIdWithRequestBuilder(makeID: makeID, xAccountID: xAccountID, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a vehicle make by ID
     - GET /api/v1/makes/{MakeID}
     - Retrieves a specific vehicle make by its unique identifier, including all associated vehicle models.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter makeID: (path) The unique identifier of the make 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MakeResponse> 
     */
    open class func getMakeByIdWithRequestBuilder(makeID: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<MakeResponse> {
        var localVariablePath = "/api/v1/makes/{MakeID}"
        let makeIDPreEscape = "\(APIHelper.mapValueToPathItem(makeID))"
        let makeIDPostEscape = makeIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{MakeID}", with: makeIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MakeResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get vehicle makes with filtering and pagination
     
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter filters: (query) The Filters query parameter (optional)
     - parameter page: (query) Page number for pagination (1-based) (optional)
     - parameter pageSize: (query) Number of items per page (optional)
     - parameter sortBy: (query) Field name to sort by (optional)
     - parameter sortDirection: (query) The SortDirection query parameter (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PagedResultOfMakeResponse
     */
    open class func getMakes(xAccountID: Int, xLocationID: Int, filters: String? = nil, page: Int? = nil, pageSize: Int? = nil, sortBy: String? = nil, sortDirection: String? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> PagedResultOfMakeResponse {
        return try await getMakesWithRequestBuilder(xAccountID: xAccountID, xLocationID: xLocationID, filters: filters, page: page, pageSize: pageSize, sortBy: sortBy, sortDirection: sortDirection, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get vehicle makes with filtering and pagination
     - GET /api/v1/makes
     - Retrieves a paginated list of vehicle makes (manufacturers) with advanced filtering and sorting capabilities.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter filters: (query) The Filters query parameter (optional)
     - parameter page: (query) Page number for pagination (1-based) (optional)
     - parameter pageSize: (query) Number of items per page (optional)
     - parameter sortBy: (query) Field name to sort by (optional)
     - parameter sortDirection: (query) The SortDirection query parameter (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PagedResultOfMakeResponse> 
     */
    open class func getMakesWithRequestBuilder(xAccountID: Int, xLocationID: Int, filters: String? = nil, page: Int? = nil, pageSize: Int? = nil, sortBy: String? = nil, sortDirection: String? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<PagedResultOfMakeResponse> {
        let localVariablePath = "/api/v1/makes"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "Filters": (wrappedValue: filters?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "Page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "PageSize": (wrappedValue: pageSize?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "SortBy": (wrappedValue: sortBy?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "SortDirection": (wrappedValue: sortDirection?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PagedResultOfMakeResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update an existing vehicle make
     
     - parameter makeID: (path) The unique identifier of the make 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter makeRequest: (body) The MakeRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MakeResponse
     */
    open class func updateMake(makeID: String, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, makeRequest: MakeRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> MakeResponse {
        return try await updateMakeWithRequestBuilder(makeID: makeID, xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, makeRequest: makeRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update an existing vehicle make
     - PUT /api/v1/makes/{MakeID}
     - Updates an existing vehicle make with partial update support (PATCH-style operations).
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter makeID: (path) The unique identifier of the make 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter makeRequest: (body) The MakeRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MakeResponse> 
     */
    open class func updateMakeWithRequestBuilder(makeID: String, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, makeRequest: MakeRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<MakeResponse> {
        var localVariablePath = "/api/v1/makes/{MakeID}"
        let makeIDPreEscape = "\(APIHelper.mapValueToPathItem(makeID))"
        let makeIDPostEscape = makeIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{MakeID}", with: makeIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: makeRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MakeResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
