//
// RolesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class RolesAPI {

    /**
     Create a new account-specific role
     
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter roleRequest: (body) The RoleRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RoleDetailResponse
     */
    open class func createRole(xKarageRequestId: String, xAccountID: Int, xLocationID: Int, roleRequest: RoleRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> RoleDetailResponse {
        return try await createRoleWithRequestBuilder(xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, roleRequest: roleRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create a new account-specific role
     - POST /api/v1/roles
     - Creates a new role for the current account with optional initial permissions and location scoping. Note: All roles automatically receive fundamental permissions (Account_Get, Account_GetList, Location_Get, Location_GetList) to allow users to see their accounts and locations.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter roleRequest: (body) The RoleRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<RoleDetailResponse> 
     */
    open class func createRoleWithRequestBuilder(xKarageRequestId: String, xAccountID: Int, xLocationID: Int, roleRequest: RoleRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<RoleDetailResponse> {
        let localVariablePath = "/api/v1/roles"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: roleRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RoleDetailResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete a role
     
     - parameter roleID: (path) The unique identifier of the Role 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteRole(roleID: String, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteRoleWithRequestBuilder(roleID: roleID, xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete a role
     - DELETE /api/v1/roles/{RoleID}
     - Deletes an account-specific role and all its associated permissions. Cannot delete roles with users assigned or system roles.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter roleID: (path) The unique identifier of the Role 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteRoleWithRequestBuilder(roleID: String, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/roles/{RoleID}"
        let roleIDPreEscape = "\(APIHelper.mapValueToPathItem(roleID))"
        let roleIDPostEscape = roleIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{RoleID}", with: roleIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get role details by ID
     
     - parameter roleID: (path) The unique identifier of the Role 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RoleDetailResponse
     */
    open class func getRoleById(roleID: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> RoleDetailResponse {
        return try await getRoleByIdWithRequestBuilder(roleID: roleID, xAccountID: xAccountID, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get role details by ID
     - GET /api/v1/roles/{RoleID}
     - Retrieves detailed information about a specific role including assigned permissions and user count.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter roleID: (path) The unique identifier of the Role 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<RoleDetailResponse> 
     */
    open class func getRoleByIdWithRequestBuilder(roleID: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<RoleDetailResponse> {
        var localVariablePath = "/api/v1/roles/{RoleID}"
        let roleIDPreEscape = "\(APIHelper.mapValueToPathItem(roleID))"
        let roleIDPostEscape = roleIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{RoleID}", with: roleIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RoleDetailResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     List all account-specific roles
     
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter filters: (query) The Filters query parameter (optional)
     - parameter page: (query) Page number for pagination (1-based) (optional)
     - parameter pageSize: (query) Number of items per page (optional)
     - parameter sortBy: (query) Field name to sort by (optional)
     - parameter sortDirection: (query) The SortDirection query parameter (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PagedResultOfRoleResponse
     */
    open class func getRoles(xAccountID: Int, xLocationID: Int, filters: String? = nil, page: Int? = nil, pageSize: Int? = nil, sortBy: String? = nil, sortDirection: String? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> PagedResultOfRoleResponse {
        return try await getRolesWithRequestBuilder(xAccountID: xAccountID, xLocationID: xLocationID, filters: filters, page: page, pageSize: pageSize, sortBy: sortBy, sortDirection: sortDirection, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     List all account-specific roles
     - GET /api/v1/roles
     - Retrieves a paginated list of roles for the current account with optional filtering by location.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter filters: (query) The Filters query parameter (optional)
     - parameter page: (query) Page number for pagination (1-based) (optional)
     - parameter pageSize: (query) Number of items per page (optional)
     - parameter sortBy: (query) Field name to sort by (optional)
     - parameter sortDirection: (query) The SortDirection query parameter (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PagedResultOfRoleResponse> 
     */
    open class func getRolesWithRequestBuilder(xAccountID: Int, xLocationID: Int, filters: String? = nil, page: Int? = nil, pageSize: Int? = nil, sortBy: String? = nil, sortDirection: String? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<PagedResultOfRoleResponse> {
        let localVariablePath = "/api/v1/roles"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "Filters": (wrappedValue: filters?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "Page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "PageSize": (wrappedValue: pageSize?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "SortBy": (wrappedValue: sortBy?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "SortDirection": (wrappedValue: sortDirection?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PagedResultOfRoleResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update an existing role
     
     - parameter roleID: (path) The unique identifier of the Role 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter roleRequest: (body) The RoleRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RoleResponse
     */
    open class func updateRole(roleID: String, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, roleRequest: RoleRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> RoleResponse {
        return try await updateRoleWithRequestBuilder(roleID: roleID, xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, roleRequest: roleRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update an existing role
     - PUT /api/v1/roles/{RoleID}
     - Updates an account-specific role's name, location scoping, and permissions. When updating permissions, the list replaces all existing permissions except for fundamental ones. Fundamental permissions (Account_Get, Account_GetList, Location_Get, Location_GetList) are automatically preserved and cannot be removed.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter roleID: (path) The unique identifier of the Role 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter roleRequest: (body) The RoleRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<RoleResponse> 
     */
    open class func updateRoleWithRequestBuilder(roleID: String, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, roleRequest: RoleRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<RoleResponse> {
        var localVariablePath = "/api/v1/roles/{RoleID}"
        let roleIDPreEscape = "\(APIHelper.mapValueToPathItem(roleID))"
        let roleIDPostEscape = roleIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{RoleID}", with: roleIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: roleRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<RoleResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
