//
// ServicesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ServicesAPI {

    /**
     Create a new service
     
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter serviceRequest: (body) The ServiceRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ServiceResponse
     */
    open class func createService(xKarageRequestId: String, xAccountID: Int, xLocationID: Int, serviceRequest: ServiceRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ServiceResponse {
        return try await createServiceWithRequestBuilder(xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, serviceRequest: serviceRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Create a new service
     - POST /api/v1/services
     - Create a new service with the specified details
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter serviceRequest: (body) The ServiceRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ServiceResponse> 
     */
    open class func createServiceWithRequestBuilder(xKarageRequestId: String, xAccountID: Int, xLocationID: Int, serviceRequest: ServiceRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<ServiceResponse> {
        let localVariablePath = "/api/v1/services"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: serviceRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Delete a service
     
     - parameter serviceID: (path) The unique identifier of the service 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteService(serviceID: String, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteServiceWithRequestBuilder(serviceID: serviceID, xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Delete a service
     - DELETE /api/v1/services/{ServiceID}
     - Delete a service by its ID
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter serviceID: (path) The unique identifier of the service 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteServiceWithRequestBuilder(serviceID: String, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/api/v1/services/{ServiceID}"
        let serviceIDPreEscape = "\(APIHelper.mapValueToPathItem(serviceID))"
        let serviceIDPostEscape = serviceIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{ServiceID}", with: serviceIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get services with dynamic filtering, pagination, and sorting
     
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter filters: (query) The Filters query parameter (optional)
     - parameter page: (query) Page number for pagination (1-based) (optional)
     - parameter pageSize: (query) Number of items per page (optional)
     - parameter sortBy: (query) Field name to sort by (optional)
     - parameter sortDirection: (query) The SortDirection query parameter (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: PagedResultOfServiceResponse
     */
    open class func getServices(xAccountID: Int, xLocationID: Int, filters: String? = nil, page: Int? = nil, pageSize: Int? = nil, sortBy: String? = nil, sortDirection: String? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> PagedResultOfServiceResponse {
        return try await getServicesWithRequestBuilder(xAccountID: xAccountID, xLocationID: xLocationID, filters: filters, page: page, pageSize: pageSize, sortBy: sortBy, sortDirection: sortDirection, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get services with dynamic filtering, pagination, and sorting
     - GET /api/v1/services
     -  Supports dynamic filtering, pagination, and sorting using the same FilterRule structure as the POST endpoint.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter filters: (query) The Filters query parameter (optional)
     - parameter page: (query) Page number for pagination (1-based) (optional)
     - parameter pageSize: (query) Number of items per page (optional)
     - parameter sortBy: (query) Field name to sort by (optional)
     - parameter sortDirection: (query) The SortDirection query parameter (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<PagedResultOfServiceResponse> 
     */
    open class func getServicesWithRequestBuilder(xAccountID: Int, xLocationID: Int, filters: String? = nil, page: Int? = nil, pageSize: Int? = nil, sortBy: String? = nil, sortDirection: String? = nil, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<PagedResultOfServiceResponse> {
        let localVariablePath = "/api/v1/services"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "Filters": (wrappedValue: filters?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "Page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "PageSize": (wrappedValue: pageSize?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "SortBy": (wrappedValue: sortBy?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "SortDirection": (wrappedValue: sortDirection?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<PagedResultOfServiceResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Get a specific service by ID
     
     - parameter serviceID: (path) The unique identifier of the service 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ServiceResponse
     */
    open class func readService(serviceID: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ServiceResponse {
        return try await readServiceWithRequestBuilder(serviceID: serviceID, xAccountID: xAccountID, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get a specific service by ID
     - GET /api/v1/services/{ServiceID}
     - Retrieve a single service using its ID
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter serviceID: (path) The unique identifier of the service 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ServiceResponse> 
     */
    open class func readServiceWithRequestBuilder(serviceID: String, xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<ServiceResponse> {
        var localVariablePath = "/api/v1/services/{ServiceID}"
        let serviceIDPreEscape = "\(APIHelper.mapValueToPathItem(serviceID))"
        let serviceIDPostEscape = serviceIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{ServiceID}", with: serviceIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**
     Update an existing service
     
     - parameter serviceID: (path) The unique identifier of the service 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter serviceRequest: (body) The ServiceRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ServiceResponse
     */
    open class func updateService(serviceID: String, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, serviceRequest: ServiceRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> ServiceResponse {
        return try await updateServiceWithRequestBuilder(serviceID: serviceID, xKarageRequestId: xKarageRequestId, xAccountID: xAccountID, xLocationID: xLocationID, serviceRequest: serviceRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Update an existing service
     - PUT /api/v1/services/{ServiceID}
     - Update a service with the specified details. Only provided fields will be updated.
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter serviceID: (path) The unique identifier of the service 
     - parameter xKarageRequestId: (header) Unique request identifier for tracing and debugging 
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter serviceRequest: (body) The ServiceRequest parameter 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ServiceResponse> 
     */
    open class func updateServiceWithRequestBuilder(serviceID: String, xKarageRequestId: String, xAccountID: Int, xLocationID: Int, serviceRequest: ServiceRequest, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<ServiceResponse> {
        var localVariablePath = "/api/v1/services/{ServiceID}"
        let serviceIDPreEscape = "\(APIHelper.mapValueToPathItem(serviceID))"
        let serviceIDPostEscape = serviceIDPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{ServiceID}", with: serviceIDPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: serviceRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "X-Karage-Request-Id": xKarageRequestId.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ServiceResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
