//
// SystemAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class SystemAPI {

    /**
     Get application version
     
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: AppVersionResponse
     */
    open class func getAppVersion(xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> AppVersionResponse {
        return try await getAppVersionWithRequestBuilder(xAccountID: xAccountID, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get application version
     - GET /api/v1/app-version
     - Returns the current application version in a legacy-compatible format with status code, message, and version data
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<AppVersionResponse> 
     */
    open class func getAppVersionWithRequestBuilder(xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<AppVersionResponse> {
        let localVariablePath = "/api/v1/app-version"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AppVersionResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }

    /**
     Get application version information
     
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: VersionInfo
     */
    open class func getVersion(xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> VersionInfo {
        return try await getVersionWithRequestBuilder(xAccountID: xAccountID, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get application version information
     - GET /api/v1/version
     - Returns minimal version information for deployment verification including semantic version, git commit hash, build date, and environment
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<VersionInfo> 
     */
    open class func getVersionWithRequestBuilder(xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<VersionInfo> {
        let localVariablePath = "/api/v1/version"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<VersionInfo>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: false, apiConfiguration: apiConfiguration)
    }
}
