//
// TechniciansAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class TechniciansAPI {

    /**
     Get all technicians for the account
     
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [TechnicianResponse]?
     */
    open class func getAllTechnicians(xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> [TechnicianResponse]? {
        return try await getAllTechniciansWithRequestBuilder(xAccountID: xAccountID, xLocationID: xLocationID, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     Get all technicians for the account
     - GET /api/v1/technicians
     -          Retrieves all users with designation 'Technician' for the authenticated account.          **Authentication Required:** Yes          **Required Headers:**         - X-Account-ID: The account identifier          **Response:**         - Returns list of technicians with their ID, name, and contact information         - Only returns active users         - Filters by designation = 'Technician'         
     - OAuth:
       - type: oauth2
       - name: OAuth2
     - parameter xAccountID: (header) The account ID to operate under (Required) 
     - parameter xLocationID: (header) The location ID to operate under (Required) 
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[TechnicianResponse]?> 
     */
    open class func getAllTechniciansWithRequestBuilder(xAccountID: Int, xLocationID: Int, apiConfiguration: KarageAPIClientAPIConfiguration = KarageAPIClientAPIConfiguration.shared) -> RequestBuilder<[TechnicianResponse]?> {
        let localVariablePath = "/api/v1/technicians"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "X-Account-ID": xAccountID.asParameter(codableHelper: apiConfiguration.codableHelper),
            "X-Location-ID": xLocationID.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[TechnicianResponse]?>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
