//
// AddOnRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AddOnRequest: Sendable, Codable, Hashable {

    public static let addOnNameRule = StringRule(minLength: 0, maxLength: 100, pattern: nil)
    public static let versionRule = StringRule(minLength: 0, maxLength: 50, pattern: nil)
    public var addOnName: String
    public var version: String?

    public init(addOnName: String, version: String? = nil) {
        self.addOnName = addOnName
        self.version = version
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case addOnName = "AddOnName"
        case version = "Version"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(addOnName, forKey: .addOnName)
        try container.encodeIfPresent(version, forKey: .version)
    }
}

