//
// BayResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BayResponse: Sendable, Codable, Hashable {

    public var bayID: Int64
    public var name: String
    public var nameAr: String?
    public var description: String?
    public var locationID: Int64
    public var locationName: String?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var statusID: StatusType

    public init(bayID: Int64, name: String, nameAr: String? = nil, description: String? = nil, locationID: Int64, locationName: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, statusID: StatusType) {
        self.bayID = bayID
        self.name = name
        self.nameAr = nameAr
        self.description = description
        self.locationID = locationID
        self.locationName = locationName
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.statusID = statusID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bayID = "BayID"
        case name = "Name"
        case nameAr = "NameAr"
        case description = "Description"
        case locationID = "LocationID"
        case locationName = "LocationName"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case statusID = "StatusID"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(bayID, forKey: .bayID)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(nameAr, forKey: .nameAr)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encode(locationID, forKey: .locationID)
        try container.encodeIfPresent(locationName, forKey: .locationName)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encode(statusID, forKey: .statusID)
    }
}

