//
// CarResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CarResponse: Sendable, Codable, Hashable {

    public var carID: Int64
    public var description: String?
    public var vinNo: String?
    public var customerID: Int64?
    public var makeID: Int64?
    public var makeName: String?
    public var modelID: Int64?
    public var modelName: String?
    public var year: Int?
    public var color: String?
    public var registrationNo: String?
    public var registrationNoArabic: String?
    public var odometer: Double?
    public var fuelType: String?
    public var oilChangeIntervalKm: Double?
    public var imagePath: String?
    public var carType: CarType
    public var carPlateType: CarPlateType
    public var createdAt: Date?
    public var updatedAt: Date?
    public var statusID: StatusType

    public init(carID: Int64, description: String? = nil, vinNo: String? = nil, customerID: Int64? = nil, makeID: Int64? = nil, makeName: String? = nil, modelID: Int64? = nil, modelName: String? = nil, year: Int? = nil, color: String? = nil, registrationNo: String? = nil, registrationNoArabic: String? = nil, odometer: Double? = nil, fuelType: String? = nil, oilChangeIntervalKm: Double? = nil, imagePath: String? = nil, carType: CarType, carPlateType: CarPlateType, createdAt: Date? = nil, updatedAt: Date? = nil, statusID: StatusType) {
        self.carID = carID
        self.description = description
        self.vinNo = vinNo
        self.customerID = customerID
        self.makeID = makeID
        self.makeName = makeName
        self.modelID = modelID
        self.modelName = modelName
        self.year = year
        self.color = color
        self.registrationNo = registrationNo
        self.registrationNoArabic = registrationNoArabic
        self.odometer = odometer
        self.fuelType = fuelType
        self.oilChangeIntervalKm = oilChangeIntervalKm
        self.imagePath = imagePath
        self.carType = carType
        self.carPlateType = carPlateType
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.statusID = statusID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case carID = "CarID"
        case description = "Description"
        case vinNo = "VinNo"
        case customerID = "CustomerID"
        case makeID = "MakeID"
        case makeName = "MakeName"
        case modelID = "ModelID"
        case modelName = "ModelName"
        case year = "Year"
        case color = "Color"
        case registrationNo = "RegistrationNo"
        case registrationNoArabic = "RegistrationNoArabic"
        case odometer = "Odometer"
        case fuelType = "FuelType"
        case oilChangeIntervalKm = "OilChangeIntervalKm"
        case imagePath = "ImagePath"
        case carType = "CarType"
        case carPlateType = "CarPlateType"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case statusID = "StatusID"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(carID, forKey: .carID)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(vinNo, forKey: .vinNo)
        try container.encodeIfPresent(customerID, forKey: .customerID)
        try container.encodeIfPresent(makeID, forKey: .makeID)
        try container.encodeIfPresent(makeName, forKey: .makeName)
        try container.encodeIfPresent(modelID, forKey: .modelID)
        try container.encodeIfPresent(modelName, forKey: .modelName)
        try container.encodeIfPresent(year, forKey: .year)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(registrationNo, forKey: .registrationNo)
        try container.encodeIfPresent(registrationNoArabic, forKey: .registrationNoArabic)
        try container.encodeIfPresent(odometer, forKey: .odometer)
        try container.encodeIfPresent(fuelType, forKey: .fuelType)
        try container.encodeIfPresent(oilChangeIntervalKm, forKey: .oilChangeIntervalKm)
        try container.encodeIfPresent(imagePath, forKey: .imagePath)
        try container.encode(carType, forKey: .carType)
        try container.encode(carPlateType, forKey: .carPlateType)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encode(statusID, forKey: .statusID)
    }
}

