//
// CategoryRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CategoryRequest: Sendable, Codable, Hashable {

    public static let nameRule = StringRule(minLength: 0, maxLength: 150, pattern: nil)
    public static let nameArRule = StringRule(minLength: 0, maxLength: 150, pattern: nil)
    public static let descriptionRule = StringRule(minLength: 0, maxLength: 500, pattern: nil)
    public static let displayOrderRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let statusIDRule = NumericRule<Int>(minimum: nil, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var name: String
    public var nameAr: String?
    public var description: String?
    public var imagePath: String?
    public var displayOrder: Int
    public var statusID: Int
    public var createdAt: Date?
    public var lastUpdatedDate: Date?

    public init(name: String, nameAr: String? = nil, description: String? = nil, imagePath: String? = nil, displayOrder: Int, statusID: Int, createdAt: Date? = nil, lastUpdatedDate: Date? = nil) {
        self.name = name
        self.nameAr = nameAr
        self.description = description
        self.imagePath = imagePath
        self.displayOrder = displayOrder
        self.statusID = statusID
        self.createdAt = createdAt
        self.lastUpdatedDate = lastUpdatedDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case nameAr = "NameAr"
        case description = "Description"
        case imagePath = "ImagePath"
        case displayOrder = "DisplayOrder"
        case statusID = "StatusID"
        case createdAt = "CreatedAt"
        case lastUpdatedDate = "LastUpdatedDate"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(nameAr, forKey: .nameAr)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(imagePath, forKey: .imagePath)
        try container.encode(displayOrder, forKey: .displayOrder)
        try container.encode(statusID, forKey: .statusID)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(lastUpdatedDate, forKey: .lastUpdatedDate)
    }
}

