//
// CityResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CityResponse: Sendable, Codable, Hashable {

    public var cityID: Int64
    public var countryID: Int64
    public var district: String
    public var timezone: String
    public var cityName: String

    public init(cityID: Int64, countryID: Int64, district: String, timezone: String, cityName: String) {
        self.cityID = cityID
        self.countryID = countryID
        self.district = district
        self.timezone = timezone
        self.cityName = cityName
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cityID = "CityID"
        case countryID = "CountryID"
        case district = "District"
        case timezone = "Timezone"
        case cityName = "CityName"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cityID, forKey: .cityID)
        try container.encode(countryID, forKey: .countryID)
        try container.encode(district, forKey: .district)
        try container.encode(timezone, forKey: .timezone)
        try container.encode(cityName, forKey: .cityName)
    }
}

