//
// CreateOrderPaymentRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateOrderPaymentRequest: Sendable, Codable, Hashable {

    public var payment: [PaymentRequest]
    public var sessionID: Int64?

    public init(payment: [PaymentRequest], sessionID: Int64? = nil) {
        self.payment = payment
        self.sessionID = sessionID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case payment = "Payment"
        case sessionID = "SessionID"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(payment, forKey: .payment)
        try container.encodeIfPresent(sessionID, forKey: .sessionID)
    }
}

