//
// CreateOAuth2ClientResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreateOAuth2ClientResponse: Sendable, Codable, Hashable {

    public var ID: String
    public var clientID: String
    public var displayName: String
    public var clientType: String
    public var consentType: String
    public var redirectUris: [String]
    public var postLogoutRedirectUris: [String]
    public var permissions: [String]
    public var requirements: [String]
    public var createdAt: Date?

    public init(ID: String, clientID: String, displayName: String, clientType: String, consentType: String, redirectUris: [String], postLogoutRedirectUris: [String], permissions: [String], requirements: [String], createdAt: Date? = nil) {
        self.ID = ID
        self.clientID = clientID
        self.displayName = displayName
        self.clientType = clientType
        self.consentType = consentType
        self.redirectUris = redirectUris
        self.postLogoutRedirectUris = postLogoutRedirectUris
        self.permissions = permissions
        self.requirements = requirements
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
        case clientID = "ClientID"
        case displayName = "DisplayName"
        case clientType = "ClientType"
        case consentType = "ConsentType"
        case redirectUris = "RedirectUris"
        case postLogoutRedirectUris = "PostLogoutRedirectUris"
        case permissions = "Permissions"
        case requirements = "Requirements"
        case createdAt = "CreatedAt"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ID, forKey: .ID)
        try container.encode(clientID, forKey: .clientID)
        try container.encode(displayName, forKey: .displayName)
        try container.encode(clientType, forKey: .clientType)
        try container.encode(consentType, forKey: .consentType)
        try container.encode(redirectUris, forKey: .redirectUris)
        try container.encode(postLogoutRedirectUris, forKey: .postLogoutRedirectUris)
        try container.encode(permissions, forKey: .permissions)
        try container.encode(requirements, forKey: .requirements)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}

