//
// CustomerStatementResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CustomerStatementResponse: Sendable, Codable, Hashable {

    public var companyClientID: Int64
    public var companyName: String
    public var fromDate: Date?
    public var toDate: Date?
    public var openingBalance: Double
    public var totalDebits: Double
    public var totalCredits: Double
    public var closingBalance: Double
    public var transactions: [StatementTransactionDto]

    public init(companyClientID: Int64, companyName: String, fromDate: Date? = nil, toDate: Date? = nil, openingBalance: Double, totalDebits: Double, totalCredits: Double, closingBalance: Double, transactions: [StatementTransactionDto]) {
        self.companyClientID = companyClientID
        self.companyName = companyName
        self.fromDate = fromDate
        self.toDate = toDate
        self.openingBalance = openingBalance
        self.totalDebits = totalDebits
        self.totalCredits = totalCredits
        self.closingBalance = closingBalance
        self.transactions = transactions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case companyClientID = "CompanyClientID"
        case companyName = "CompanyName"
        case fromDate = "FromDate"
        case toDate = "ToDate"
        case openingBalance = "OpeningBalance"
        case totalDebits = "TotalDebits"
        case totalCredits = "TotalCredits"
        case closingBalance = "ClosingBalance"
        case transactions = "Transactions"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(companyClientID, forKey: .companyClientID)
        try container.encode(companyName, forKey: .companyName)
        try container.encodeIfPresent(fromDate, forKey: .fromDate)
        try container.encodeIfPresent(toDate, forKey: .toDate)
        try container.encode(openingBalance, forKey: .openingBalance)
        try container.encode(totalDebits, forKey: .totalDebits)
        try container.encode(totalCredits, forKey: .totalCredits)
        try container.encode(closingBalance, forKey: .closingBalance)
        try container.encode(transactions, forKey: .transactions)
    }
}

