//
// DiscountUsageItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Discount usage summary */
public struct DiscountUsageItem: Sendable, Codable, Hashable {

    /** Discount ID */
    public var discountID: Int64
    /** Discount name */
    public var name: String
    /** Number of times the discount was applied */
    public var appliedCount: Int
    /** Total discount amount given */
    public var totalAmount: Double
    /** Percentage of total discounts */
    public var percentage: Double

    public init(discountID: Int64, name: String, appliedCount: Int, totalAmount: Double, percentage: Double) {
        self.discountID = discountID
        self.name = name
        self.appliedCount = appliedCount
        self.totalAmount = totalAmount
        self.percentage = percentage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case discountID = "DiscountID"
        case name = "Name"
        case appliedCount = "AppliedCount"
        case totalAmount = "TotalAmount"
        case percentage = "Percentage"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(discountID, forKey: .discountID)
        try container.encode(name, forKey: .name)
        try container.encode(appliedCount, forKey: .appliedCount)
        try container.encode(totalAmount, forKey: .totalAmount)
        try container.encode(percentage, forKey: .percentage)
    }
}

