//
// DiscountItemRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DiscountItemRequest: Sendable, Codable, Hashable {

    public var itemID: Int64
    public var role: DiscountItemRole

    public init(itemID: Int64, role: DiscountItemRole) {
        self.itemID = itemID
        self.role = role
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case itemID = "ItemID"
        case role = "Role"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(itemID, forKey: .itemID)
        try container.encode(role, forKey: .role)
    }
}

