//
// EmployeeTargetItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Employee performance/target item */
public struct EmployeeTargetItem: Sendable, Codable, Hashable {

    /** Employee user ID */
    public var employeeID: Int64
    /** Employee name */
    public var name: String
    /** Number of orders handled */
    public var orderCount: Int
    /** Total sales amount */
    public var totalAmount: Double

    public init(employeeID: Int64, name: String, orderCount: Int, totalAmount: Double) {
        self.employeeID = employeeID
        self.name = name
        self.orderCount = orderCount
        self.totalAmount = totalAmount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case employeeID = "EmployeeID"
        case name = "Name"
        case orderCount = "OrderCount"
        case totalAmount = "TotalAmount"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(employeeID, forKey: .employeeID)
        try container.encode(name, forKey: .name)
        try container.encode(orderCount, forKey: .orderCount)
        try container.encode(totalAmount, forKey: .totalAmount)
    }
}

