//
// GenerateUploadSasTokenRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request to generate a SAS token for file upload */
public struct GenerateUploadSasTokenRequest: Sendable, Codable, Hashable {

    public static let fileNameRule = StringRule(minLength: 0, maxLength: 255, pattern: nil)
    public static let containerNameRule = StringRule(minLength: 0, maxLength: 63, pattern: "/^[a-z0-9](?:[a-z0-9\\-]*[a-z0-9])?$/")
    public static let folderPathRule = StringRule(minLength: 0, maxLength: 1024, pattern: nil)
    public static let expirationMinutesRule = NumericRule<Int>(minimum: 5, exclusiveMinimum: false, maximum: 1440, exclusiveMaximum: false, multipleOf: nil)
    /** The name of the file to upload (including extension). Required for validation and blob naming. Example: \"invoice-12345.pdf\" */
    public var fileName: String
    /** Optional container name. If not specified, uses the default container from configuration. Example: \"invoices\", \"receipts\", \"documents\" */
    public var containerName: String?
    /** Optional folder path within the container for organizing files. Example: \"2024/01\", \"customers/12345\", \"uploads\" */
    public var folderPath: String?
    /** Optional custom expiration time in minutes. If not specified, uses the default expiration from configuration. Minimum: 5 minutes, Maximum: 1440 minutes (24 hours) */
    public var expirationMinutes: Int?

    public init(fileName: String, containerName: String? = nil, folderPath: String? = nil, expirationMinutes: Int? = nil) {
        self.fileName = fileName
        self.containerName = containerName
        self.folderPath = folderPath
        self.expirationMinutes = expirationMinutes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fileName = "FileName"
        case containerName = "ContainerName"
        case folderPath = "FolderPath"
        case expirationMinutes = "ExpirationMinutes"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fileName, forKey: .fileName)
        try container.encodeIfPresent(containerName, forKey: .containerName)
        try container.encodeIfPresent(folderPath, forKey: .folderPath)
        try container.encodeIfPresent(expirationMinutes, forKey: .expirationMinutes)
    }
}

