//
// GenerateDownloadSasTokenResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response containing the SAS token for file download */
public struct GenerateDownloadSasTokenResponse: Sendable, Codable, Hashable {

    /** The blob name (file path) in the storage container. Null for account-level or container-level SAS tokens. */
    public var blobName: String?
    /** The full SAS URL to use for downloading files. For blob-level SAS: direct download URL for the specific file. For container-level SAS: base URL for the container, append blob name to download specific files. For account-level SAS: base URL for the account, append container/blob path to download specific files. Use HTTP GET method to download. */
    public var downloadUrl: String
    /** The expiration time of the SAS token (UTC). Download must be initiated before this time. */
    public var expiresOn: Date
    /** The HTTP method to use for downloading files. Always \"GET\" for Azure Blob Storage downloads. */
    public var downloadMethod: String
    /** The scope of the SAS token. \"blob\": specific file, \"container\": all files in container, \"account\": all files in all containers. */
    public var sasScope: String

    public init(blobName: String? = nil, downloadUrl: String, expiresOn: Date, downloadMethod: String, sasScope: String) {
        self.blobName = blobName
        self.downloadUrl = downloadUrl
        self.expiresOn = expiresOn
        self.downloadMethod = downloadMethod
        self.sasScope = sasScope
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blobName = "BlobName"
        case downloadUrl = "DownloadUrl"
        case expiresOn = "ExpiresOn"
        case downloadMethod = "DownloadMethod"
        case sasScope = "SasScope"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(blobName, forKey: .blobName)
        try container.encode(downloadUrl, forKey: .downloadUrl)
        try container.encode(expiresOn, forKey: .expiresOn)
        try container.encode(downloadMethod, forKey: .downloadMethod)
        try container.encode(sasScope, forKey: .sasScope)
    }
}

