//
// InvoiceAllocationDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct InvoiceAllocationDto: Sendable, Codable, Hashable {

    public static let invoiceIDRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: true, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let amountDueRule = NumericRule<Double>(minimum: 0.0, exclusiveMinimum: true, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let receivedAmountRule = NumericRule<Double>(minimum: 0.0, exclusiveMinimum: true, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var invoiceID: Int64 = 1
    public var invoiceNo: String?
    public var invoiceDate: Date?
    public var invoiceAmount: Double?
    public var amountDue: Double = 100.0
    public var paymentReceivedDate: Date = Date(timeIntervalSince1970: 1704067200000000.0 / 1_000_000)
    public var receivedAmount: Double = 50.0

    public init(invoiceID: Int64 = 1, invoiceNo: String? = nil, invoiceDate: Date? = nil, invoiceAmount: Double? = nil, amountDue: Double = 100.0, paymentReceivedDate: Date = Date(timeIntervalSince1970: 1704067200000000.0 / 1_000_000), receivedAmount: Double = 50.0) {
        self.invoiceID = invoiceID
        self.invoiceNo = invoiceNo
        self.invoiceDate = invoiceDate
        self.invoiceAmount = invoiceAmount
        self.amountDue = amountDue
        self.paymentReceivedDate = paymentReceivedDate
        self.receivedAmount = receivedAmount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case invoiceID = "InvoiceID"
        case invoiceNo = "InvoiceNo"
        case invoiceDate = "InvoiceDate"
        case invoiceAmount = "InvoiceAmount"
        case amountDue = "AmountDue"
        case paymentReceivedDate = "PaymentReceivedDate"
        case receivedAmount = "ReceivedAmount"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(invoiceID, forKey: .invoiceID)
        try container.encodeIfPresent(invoiceNo, forKey: .invoiceNo)
        try container.encodeIfPresent(invoiceDate, forKey: .invoiceDate)
        try container.encodeIfPresent(invoiceAmount, forKey: .invoiceAmount)
        try container.encode(amountDue, forKey: .amountDue)
        try container.encode(paymentReceivedDate, forKey: .paymentReceivedDate)
        try container.encode(receivedAmount, forKey: .receivedAmount)
    }
}

