//
// ItemResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ItemResponse: Sendable, Codable, Hashable {

    public var itemID: Int64
    public var categoryID: Int64
    public var name: String
    public var nameAr: String?
    public var description: String?
    public var imagePath: String?
    public var barcode: String?
    public var SKU: String?
    public var displayOrder: Int
    public var cost: Double
    public var price: Double
    public var itemTypeID: Int64
    public var propertiesJSON: String?
    public var isInventoryItem: Bool
    public var isOpenItem: Bool
    public var minOpenPrice: Double?
    public var isInclusiveVAT: Bool
    public var priceInclusiveVAT: Double?
    public var reorderLevel: Int?
    public var taxID: Int64?
    public var taxRate: Double?
    public var taxValue: Double
    public var createdAt: Date?
    public var updatedAt: Date?
    public var statusID: StatusType
    public var locationItems: [LocationItemResponse]

    public init(itemID: Int64, categoryID: Int64, name: String, nameAr: String? = nil, description: String? = nil, imagePath: String? = nil, barcode: String? = nil, SKU: String? = nil, displayOrder: Int, cost: Double, price: Double, itemTypeID: Int64, propertiesJSON: String? = nil, isInventoryItem: Bool, isOpenItem: Bool, minOpenPrice: Double? = nil, isInclusiveVAT: Bool, priceInclusiveVAT: Double? = nil, reorderLevel: Int? = nil, taxID: Int64? = nil, taxRate: Double? = nil, taxValue: Double, createdAt: Date? = nil, updatedAt: Date? = nil, statusID: StatusType, locationItems: [LocationItemResponse]) {
        self.itemID = itemID
        self.categoryID = categoryID
        self.name = name
        self.nameAr = nameAr
        self.description = description
        self.imagePath = imagePath
        self.barcode = barcode
        self.SKU = SKU
        self.displayOrder = displayOrder
        self.cost = cost
        self.price = price
        self.itemTypeID = itemTypeID
        self.propertiesJSON = propertiesJSON
        self.isInventoryItem = isInventoryItem
        self.isOpenItem = isOpenItem
        self.minOpenPrice = minOpenPrice
        self.isInclusiveVAT = isInclusiveVAT
        self.priceInclusiveVAT = priceInclusiveVAT
        self.reorderLevel = reorderLevel
        self.taxID = taxID
        self.taxRate = taxRate
        self.taxValue = taxValue
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.statusID = statusID
        self.locationItems = locationItems
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case itemID = "ItemID"
        case categoryID = "CategoryID"
        case name = "Name"
        case nameAr = "NameAr"
        case description = "Description"
        case imagePath = "ImagePath"
        case barcode = "Barcode"
        case SKU
        case displayOrder = "DisplayOrder"
        case cost = "Cost"
        case price = "Price"
        case itemTypeID = "ItemTypeID"
        case propertiesJSON = "PropertiesJSON"
        case isInventoryItem = "IsInventoryItem"
        case isOpenItem = "IsOpenItem"
        case minOpenPrice = "MinOpenPrice"
        case isInclusiveVAT = "IsInclusiveVAT"
        case priceInclusiveVAT = "PriceInclusiveVAT"
        case reorderLevel = "ReorderLevel"
        case taxID = "TaxID"
        case taxRate = "TaxRate"
        case taxValue = "TaxValue"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case statusID = "StatusID"
        case locationItems = "LocationItems"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(itemID, forKey: .itemID)
        try container.encode(categoryID, forKey: .categoryID)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(nameAr, forKey: .nameAr)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(imagePath, forKey: .imagePath)
        try container.encodeIfPresent(barcode, forKey: .barcode)
        try container.encodeIfPresent(SKU, forKey: .SKU)
        try container.encode(displayOrder, forKey: .displayOrder)
        try container.encode(cost, forKey: .cost)
        try container.encode(price, forKey: .price)
        try container.encode(itemTypeID, forKey: .itemTypeID)
        try container.encodeIfPresent(propertiesJSON, forKey: .propertiesJSON)
        try container.encode(isInventoryItem, forKey: .isInventoryItem)
        try container.encode(isOpenItem, forKey: .isOpenItem)
        try container.encodeIfPresent(minOpenPrice, forKey: .minOpenPrice)
        try container.encode(isInclusiveVAT, forKey: .isInclusiveVAT)
        try container.encodeIfPresent(priceInclusiveVAT, forKey: .priceInclusiveVAT)
        try container.encodeIfPresent(reorderLevel, forKey: .reorderLevel)
        try container.encodeIfPresent(taxID, forKey: .taxID)
        try container.encodeIfPresent(taxRate, forKey: .taxRate)
        try container.encode(taxValue, forKey: .taxValue)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encode(statusID, forKey: .statusID)
        try container.encode(locationItems, forKey: .locationItems)
    }
}

