//
// JobOrderSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct JobOrderSettings: Sendable, Codable, Hashable {

    public var isSunmi: Bool
    public var isA4: Bool

    public init(isSunmi: Bool, isA4: Bool) {
        self.isSunmi = isSunmi
        self.isA4 = isA4
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isSunmi = "IsSunmi"
        case isA4 = "IsA4"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isSunmi, forKey: .isSunmi)
        try container.encode(isA4, forKey: .isA4)
    }
}

