//
// KashierSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct KashierSettings: Sendable, Codable, Hashable {

    public var jobOrder: JobOrderSettings
    public var hasCheckList: Bool
    public var hasNotes: Bool

    public init(jobOrder: JobOrderSettings, hasCheckList: Bool, hasNotes: Bool) {
        self.jobOrder = jobOrder
        self.hasCheckList = hasCheckList
        self.hasNotes = hasNotes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case jobOrder = "JobOrder"
        case hasCheckList = "HasCheckList"
        case hasNotes = "HasNotes"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(jobOrder, forKey: .jobOrder)
        try container.encode(hasCheckList, forKey: .hasCheckList)
        try container.encode(hasNotes, forKey: .hasNotes)
    }
}

