//
// LiteSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LiteSettings: Sendable, Codable, Hashable {

    public var isCustomerMandatoryOnCheckout: Bool

    public init(isCustomerMandatoryOnCheckout: Bool) {
        self.isCustomerMandatoryOnCheckout = isCustomerMandatoryOnCheckout
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case isCustomerMandatoryOnCheckout = "IsCustomerMandatoryOnCheckout"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(isCustomerMandatoryOnCheckout, forKey: .isCustomerMandatoryOnCheckout)
    }
}

