//
// MakeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MakeRequest: Sendable, Codable, Hashable {

    public static let nameRule = StringRule(minLength: 0, maxLength: 150, pattern: "/^[A-Za-z0-9\\s\\-_.]*$/")
    public static let nameArRule = StringRule(minLength: 0, maxLength: 150, pattern: "/^[\\u0600-\\u06FF\\s]*$/")
    public static let imagePathRule = StringRule(minLength: 0, maxLength: 2048, pattern: nil)
    public static let displayOrderRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var name: String
    public var nameAr: String?
    public var imagePath: String?
    public var displayOrder: Int?
    public var statusID: StatusType?

    public init(name: String, nameAr: String? = nil, imagePath: String? = nil, displayOrder: Int? = nil, statusID: StatusType? = nil) {
        self.name = name
        self.nameAr = nameAr
        self.imagePath = imagePath
        self.displayOrder = displayOrder
        self.statusID = statusID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case nameAr = "NameAr"
        case imagePath = "ImagePath"
        case displayOrder = "DisplayOrder"
        case statusID = "StatusID"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(nameAr, forKey: .nameAr)
        try container.encodeIfPresent(imagePath, forKey: .imagePath)
        try container.encodeIfPresent(displayOrder, forKey: .displayOrder)
        try container.encodeIfPresent(statusID, forKey: .statusID)
    }
}

