//
// ModelRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModelRequest: Sendable, Codable, Hashable {

    public static let makeIDRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: true, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let nameRule = StringRule(minLength: 0, maxLength: 150, pattern: "/^[A-Za-z0-9\\s\\-_.]*$/")
    public static let nameArRule = StringRule(minLength: 0, maxLength: 150, pattern: "/^[\\u0600-\\u06FF\\s]*$/")
    public static let yearRule = NumericRule<Int>(minimum: 1900, exclusiveMinimum: false, maximum: 2100, exclusiveMaximum: false, multipleOf: nil)
    public static let engineNoRule = StringRule(minLength: 0, maxLength: 50, pattern: "/^[A-Za-z0-9\\-_]*$/")
    public static let recommendedLitersRule = NumericRule<Double>(minimum: 0.0, exclusiveMinimum: false, maximum: 1000.0, exclusiveMaximum: false, multipleOf: nil)
    public static let imagePathRule = StringRule(minLength: 0, maxLength: 2048, pattern: nil)
    public static let displayOrderRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var makeID: Int64
    public var name: String
    public var nameAr: String?
    public var year: Int
    public var engineNo: String?
    public var recommendedLiters: Double?
    public var imagePath: String?
    public var displayOrder: Int?
    public var statusID: StatusType?

    public init(makeID: Int64, name: String, nameAr: String? = nil, year: Int, engineNo: String? = nil, recommendedLiters: Double? = nil, imagePath: String? = nil, displayOrder: Int? = nil, statusID: StatusType? = nil) {
        self.makeID = makeID
        self.name = name
        self.nameAr = nameAr
        self.year = year
        self.engineNo = engineNo
        self.recommendedLiters = recommendedLiters
        self.imagePath = imagePath
        self.displayOrder = displayOrder
        self.statusID = statusID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case makeID = "MakeID"
        case name = "Name"
        case nameAr = "NameAr"
        case year = "Year"
        case engineNo = "EngineNo"
        case recommendedLiters = "RecommendedLiters"
        case imagePath = "ImagePath"
        case displayOrder = "DisplayOrder"
        case statusID = "StatusID"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(makeID, forKey: .makeID)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(nameAr, forKey: .nameAr)
        try container.encode(year, forKey: .year)
        try container.encodeIfPresent(engineNo, forKey: .engineNo)
        try container.encodeIfPresent(recommendedLiters, forKey: .recommendedLiters)
        try container.encodeIfPresent(imagePath, forKey: .imagePath)
        try container.encodeIfPresent(displayOrder, forKey: .displayOrder)
        try container.encodeIfPresent(statusID, forKey: .statusID)
    }
}

