//
// OAuth2ClientSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OAuth2ClientSummary: Sendable, Codable, Hashable {

    public var ID: String
    public var clientID: String
    public var displayName: String
    public var clientType: String
    public var consentType: String
    public var redirectUriCount: Int
    public var permissionCount: Int

    public init(ID: String, clientID: String, displayName: String, clientType: String, consentType: String, redirectUriCount: Int, permissionCount: Int) {
        self.ID = ID
        self.clientID = clientID
        self.displayName = displayName
        self.clientType = clientType
        self.consentType = consentType
        self.redirectUriCount = redirectUriCount
        self.permissionCount = permissionCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
        case clientID = "ClientID"
        case displayName = "DisplayName"
        case clientType = "ClientType"
        case consentType = "ConsentType"
        case redirectUriCount = "RedirectUriCount"
        case permissionCount = "PermissionCount"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ID, forKey: .ID)
        try container.encode(clientID, forKey: .clientID)
        try container.encode(displayName, forKey: .displayName)
        try container.encode(clientType, forKey: .clientType)
        try container.encode(consentType, forKey: .consentType)
        try container.encode(redirectUriCount, forKey: .redirectUriCount)
        try container.encode(permissionCount, forKey: .permissionCount)
    }
}

