//
// OrderLocationResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OrderLocationResponse: Sendable, Codable, Hashable {

    public var locationID: Int64
    public var accountID: Int64?
    public var cityID: Int64?
    public var countryID: Int64?
    public var landmarkID: Int64?
    public var name: String
    public var nameAr: String?
    public var description: String?
    public var descriptionAr: String?
    public var representativeName: String?
    public var representativeContactNo: String?
    public var contactNo: String?
    public var email: String?
    public var shortAddress: String?
    public var buildingNumber: String?
    public var streetName: String?
    public var secondaryNumber: String?
    public var district: String?
    public var postalCode: String?
    public var address1: String?
    public var address1Ar: String?
    public var address2: String?
    public var address2Ar: String?
    public var countryName: String?
    public var cityName: String?
    public var socialMedias: [String: String]?
    public var amenities: [String]?
    public var services: [String]?
    public var locationImages: [String]?
    public var workingHours: String?
    public var gMapLink: String?
    public var longitude: Double?
    public var latitude: Double?
    public var isFeatured: Bool
    public var isHQ: Bool
    public var isActiveMyKarage: Bool
    public var vATNo: String?
    public var cRNo: String?
    public var settings: TypedLocationSettingsResponse?

    public init(locationID: Int64, accountID: Int64? = nil, cityID: Int64? = nil, countryID: Int64? = nil, landmarkID: Int64? = nil, name: String, nameAr: String? = nil, description: String? = nil, descriptionAr: String? = nil, representativeName: String? = nil, representativeContactNo: String? = nil, contactNo: String? = nil, email: String? = nil, shortAddress: String? = nil, buildingNumber: String? = nil, streetName: String? = nil, secondaryNumber: String? = nil, district: String? = nil, postalCode: String? = nil, address1: String? = nil, address1Ar: String? = nil, address2: String? = nil, address2Ar: String? = nil, countryName: String? = nil, cityName: String? = nil, socialMedias: [String: String]? = nil, amenities: [String]? = nil, services: [String]? = nil, locationImages: [String]? = nil, workingHours: String? = nil, gMapLink: String? = nil, longitude: Double? = nil, latitude: Double? = nil, isFeatured: Bool, isHQ: Bool, isActiveMyKarage: Bool, vATNo: String? = nil, cRNo: String? = nil, settings: TypedLocationSettingsResponse? = nil) {
        self.locationID = locationID
        self.accountID = accountID
        self.cityID = cityID
        self.countryID = countryID
        self.landmarkID = landmarkID
        self.name = name
        self.nameAr = nameAr
        self.description = description
        self.descriptionAr = descriptionAr
        self.representativeName = representativeName
        self.representativeContactNo = representativeContactNo
        self.contactNo = contactNo
        self.email = email
        self.shortAddress = shortAddress
        self.buildingNumber = buildingNumber
        self.streetName = streetName
        self.secondaryNumber = secondaryNumber
        self.district = district
        self.postalCode = postalCode
        self.address1 = address1
        self.address1Ar = address1Ar
        self.address2 = address2
        self.address2Ar = address2Ar
        self.countryName = countryName
        self.cityName = cityName
        self.socialMedias = socialMedias
        self.amenities = amenities
        self.services = services
        self.locationImages = locationImages
        self.workingHours = workingHours
        self.gMapLink = gMapLink
        self.longitude = longitude
        self.latitude = latitude
        self.isFeatured = isFeatured
        self.isHQ = isHQ
        self.isActiveMyKarage = isActiveMyKarage
        self.vATNo = vATNo
        self.cRNo = cRNo
        self.settings = settings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case locationID = "LocationID"
        case accountID = "AccountID"
        case cityID = "CityID"
        case countryID = "CountryID"
        case landmarkID = "LandmarkID"
        case name = "Name"
        case nameAr = "NameAr"
        case description = "Description"
        case descriptionAr = "DescriptionAr"
        case representativeName = "RepresentativeName"
        case representativeContactNo = "RepresentativeContactNo"
        case contactNo = "ContactNo"
        case email = "Email"
        case shortAddress = "ShortAddress"
        case buildingNumber = "BuildingNumber"
        case streetName = "StreetName"
        case secondaryNumber = "SecondaryNumber"
        case district = "District"
        case postalCode = "PostalCode"
        case address1 = "Address1"
        case address1Ar = "Address1Ar"
        case address2 = "Address2"
        case address2Ar = "Address2Ar"
        case countryName = "CountryName"
        case cityName = "CityName"
        case socialMedias = "SocialMedias"
        case amenities = "Amenities"
        case services = "Services"
        case locationImages = "LocationImages"
        case workingHours = "WorkingHours"
        case gMapLink = "GMapLink"
        case longitude = "Longitude"
        case latitude = "Latitude"
        case isFeatured = "IsFeatured"
        case isHQ = "IsHQ"
        case isActiveMyKarage = "IsActiveMyKarage"
        case vATNo = "VATNo"
        case cRNo = "CRNo"
        case settings = "Settings"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(locationID, forKey: .locationID)
        try container.encodeIfPresent(accountID, forKey: .accountID)
        try container.encodeIfPresent(cityID, forKey: .cityID)
        try container.encodeIfPresent(countryID, forKey: .countryID)
        try container.encodeIfPresent(landmarkID, forKey: .landmarkID)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(nameAr, forKey: .nameAr)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(descriptionAr, forKey: .descriptionAr)
        try container.encodeIfPresent(representativeName, forKey: .representativeName)
        try container.encodeIfPresent(representativeContactNo, forKey: .representativeContactNo)
        try container.encodeIfPresent(contactNo, forKey: .contactNo)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(shortAddress, forKey: .shortAddress)
        try container.encodeIfPresent(buildingNumber, forKey: .buildingNumber)
        try container.encodeIfPresent(streetName, forKey: .streetName)
        try container.encodeIfPresent(secondaryNumber, forKey: .secondaryNumber)
        try container.encodeIfPresent(district, forKey: .district)
        try container.encodeIfPresent(postalCode, forKey: .postalCode)
        try container.encodeIfPresent(address1, forKey: .address1)
        try container.encodeIfPresent(address1Ar, forKey: .address1Ar)
        try container.encodeIfPresent(address2, forKey: .address2)
        try container.encodeIfPresent(address2Ar, forKey: .address2Ar)
        try container.encodeIfPresent(countryName, forKey: .countryName)
        try container.encodeIfPresent(cityName, forKey: .cityName)
        try container.encodeIfPresent(socialMedias, forKey: .socialMedias)
        try container.encodeIfPresent(amenities, forKey: .amenities)
        try container.encodeIfPresent(services, forKey: .services)
        try container.encodeIfPresent(locationImages, forKey: .locationImages)
        try container.encodeIfPresent(workingHours, forKey: .workingHours)
        try container.encodeIfPresent(gMapLink, forKey: .gMapLink)
        try container.encodeIfPresent(longitude, forKey: .longitude)
        try container.encodeIfPresent(latitude, forKey: .latitude)
        try container.encode(isFeatured, forKey: .isFeatured)
        try container.encode(isHQ, forKey: .isHQ)
        try container.encode(isActiveMyKarage, forKey: .isActiveMyKarage)
        try container.encodeIfPresent(vATNo, forKey: .vATNo)
        try container.encodeIfPresent(cRNo, forKey: .cRNo)
        try container.encodeIfPresent(settings, forKey: .settings)
    }
}

