//
// OrderResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OrderResponse: Sendable, Codable, Hashable {

    public var orderID: Int64
    public var transactionNo: Int64
    public var orderNo: Int64
    public var sessionID: Int64?
    public var sessionNo: Int64?
    public var carID: Int64?
    public var customerID: Int64?
    public var companyClientID: Int64?
    public var bayID: Int64?
    public var bayName: String?
    public var orderType: OrderType?
    public var orderTakerID: Int64
    public var orderTakerName: String?
    public var locationID: Int64
    public var discountID: Int64?
    public var discountCode: String?
    public var discountName: String?
    public var discount: DiscountResponse?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var lastServiceStatusID: ServiceStatusType
    public var subtotal: Double
    public var itemDiscountTotal: Double
    public var itemDiscountPercent: Double
    public var discountAmount: Double
    public var tax: Double
    public var additionalCharges: Double
    public var grandTotal: Double
    public var amountPaid: Double
    public var orderAmountPending: Double
    public var taxPercent: Double
    public var discountPercent: Double
    public var refundAmount: Double
    public var refund: RefundSummary?
    public var lastOrderPaymentStatusID: OrderPaymentStatusType
    public var isCompleted: Bool
    public var technicians: [TechnicianResponse]
    public var lineItems: [LineItemResponse]
    public var orderHistory: OrderHistoryResponse?
    public var orderNotes: [OrderNoteResponse]
    public var payments: [PaymentResponse]
    public var car: CarResponse?
    public var customer: CustomerResponse?
    public var companyClient: CompanyClientResponse?
    public var location: OrderLocationResponse?
    public var zatcaStatus: String?
    public var zatcaClearanceStatus: String?
    public var zatcaInvoiceUUID: String?
    public var zatcaQRCode: String?
    public var zatcaSubmittedAt: Date?
    public var zatcaErrorMessage: String?

    public init(orderID: Int64, transactionNo: Int64, orderNo: Int64, sessionID: Int64? = nil, sessionNo: Int64? = nil, carID: Int64? = nil, customerID: Int64? = nil, companyClientID: Int64? = nil, bayID: Int64? = nil, bayName: String? = nil, orderType: OrderType? = nil, orderTakerID: Int64, orderTakerName: String? = nil, locationID: Int64, discountID: Int64? = nil, discountCode: String? = nil, discountName: String? = nil, discount: DiscountResponse? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, lastServiceStatusID: ServiceStatusType, subtotal: Double, itemDiscountTotal: Double, itemDiscountPercent: Double, discountAmount: Double, tax: Double, additionalCharges: Double, grandTotal: Double, amountPaid: Double, orderAmountPending: Double, taxPercent: Double, discountPercent: Double, refundAmount: Double, refund: RefundSummary? = nil, lastOrderPaymentStatusID: OrderPaymentStatusType, isCompleted: Bool, technicians: [TechnicianResponse], lineItems: [LineItemResponse], orderHistory: OrderHistoryResponse? = nil, orderNotes: [OrderNoteResponse], payments: [PaymentResponse], car: CarResponse? = nil, customer: CustomerResponse? = nil, companyClient: CompanyClientResponse? = nil, location: OrderLocationResponse? = nil, zatcaStatus: String? = nil, zatcaClearanceStatus: String? = nil, zatcaInvoiceUUID: String? = nil, zatcaQRCode: String? = nil, zatcaSubmittedAt: Date? = nil, zatcaErrorMessage: String? = nil) {
        self.orderID = orderID
        self.transactionNo = transactionNo
        self.orderNo = orderNo
        self.sessionID = sessionID
        self.sessionNo = sessionNo
        self.carID = carID
        self.customerID = customerID
        self.companyClientID = companyClientID
        self.bayID = bayID
        self.bayName = bayName
        self.orderType = orderType
        self.orderTakerID = orderTakerID
        self.orderTakerName = orderTakerName
        self.locationID = locationID
        self.discountID = discountID
        self.discountCode = discountCode
        self.discountName = discountName
        self.discount = discount
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.lastServiceStatusID = lastServiceStatusID
        self.subtotal = subtotal
        self.itemDiscountTotal = itemDiscountTotal
        self.itemDiscountPercent = itemDiscountPercent
        self.discountAmount = discountAmount
        self.tax = tax
        self.additionalCharges = additionalCharges
        self.grandTotal = grandTotal
        self.amountPaid = amountPaid
        self.orderAmountPending = orderAmountPending
        self.taxPercent = taxPercent
        self.discountPercent = discountPercent
        self.refundAmount = refundAmount
        self.refund = refund
        self.lastOrderPaymentStatusID = lastOrderPaymentStatusID
        self.isCompleted = isCompleted
        self.technicians = technicians
        self.lineItems = lineItems
        self.orderHistory = orderHistory
        self.orderNotes = orderNotes
        self.payments = payments
        self.car = car
        self.customer = customer
        self.companyClient = companyClient
        self.location = location
        self.zatcaStatus = zatcaStatus
        self.zatcaClearanceStatus = zatcaClearanceStatus
        self.zatcaInvoiceUUID = zatcaInvoiceUUID
        self.zatcaQRCode = zatcaQRCode
        self.zatcaSubmittedAt = zatcaSubmittedAt
        self.zatcaErrorMessage = zatcaErrorMessage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case orderID = "OrderID"
        case transactionNo = "TransactionNo"
        case orderNo = "OrderNo"
        case sessionID = "SessionID"
        case sessionNo = "SessionNo"
        case carID = "CarID"
        case customerID = "CustomerID"
        case companyClientID = "CompanyClientID"
        case bayID = "BayID"
        case bayName = "BayName"
        case orderType = "OrderType"
        case orderTakerID = "OrderTakerID"
        case orderTakerName = "OrderTakerName"
        case locationID = "LocationID"
        case discountID = "DiscountID"
        case discountCode = "DiscountCode"
        case discountName = "DiscountName"
        case discount = "Discount"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case lastServiceStatusID = "LastServiceStatusID"
        case subtotal = "Subtotal"
        case itemDiscountTotal = "ItemDiscountTotal"
        case itemDiscountPercent = "ItemDiscountPercent"
        case discountAmount = "DiscountAmount"
        case tax = "Tax"
        case additionalCharges = "AdditionalCharges"
        case grandTotal = "GrandTotal"
        case amountPaid = "AmountPaid"
        case orderAmountPending = "OrderAmountPending"
        case taxPercent = "TaxPercent"
        case discountPercent = "DiscountPercent"
        case refundAmount = "RefundAmount"
        case refund = "Refund"
        case lastOrderPaymentStatusID = "LastOrderPaymentStatusID"
        case isCompleted = "IsCompleted"
        case technicians = "Technicians"
        case lineItems = "LineItems"
        case orderHistory = "OrderHistory"
        case orderNotes = "OrderNotes"
        case payments = "Payments"
        case car = "Car"
        case customer = "Customer"
        case companyClient = "CompanyClient"
        case location = "Location"
        case zatcaStatus = "ZatcaStatus"
        case zatcaClearanceStatus = "ZatcaClearanceStatus"
        case zatcaInvoiceUUID = "ZatcaInvoiceUUID"
        case zatcaQRCode = "ZatcaQRCode"
        case zatcaSubmittedAt = "ZatcaSubmittedAt"
        case zatcaErrorMessage = "ZatcaErrorMessage"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(orderID, forKey: .orderID)
        try container.encode(transactionNo, forKey: .transactionNo)
        try container.encode(orderNo, forKey: .orderNo)
        try container.encodeIfPresent(sessionID, forKey: .sessionID)
        try container.encodeIfPresent(sessionNo, forKey: .sessionNo)
        try container.encodeIfPresent(carID, forKey: .carID)
        try container.encodeIfPresent(customerID, forKey: .customerID)
        try container.encodeIfPresent(companyClientID, forKey: .companyClientID)
        try container.encodeIfPresent(bayID, forKey: .bayID)
        try container.encodeIfPresent(bayName, forKey: .bayName)
        try container.encodeIfPresent(orderType, forKey: .orderType)
        try container.encode(orderTakerID, forKey: .orderTakerID)
        try container.encodeIfPresent(orderTakerName, forKey: .orderTakerName)
        try container.encode(locationID, forKey: .locationID)
        try container.encodeIfPresent(discountID, forKey: .discountID)
        try container.encodeIfPresent(discountCode, forKey: .discountCode)
        try container.encodeIfPresent(discountName, forKey: .discountName)
        try container.encodeIfPresent(discount, forKey: .discount)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encode(lastServiceStatusID, forKey: .lastServiceStatusID)
        try container.encode(subtotal, forKey: .subtotal)
        try container.encode(itemDiscountTotal, forKey: .itemDiscountTotal)
        try container.encode(itemDiscountPercent, forKey: .itemDiscountPercent)
        try container.encode(discountAmount, forKey: .discountAmount)
        try container.encode(tax, forKey: .tax)
        try container.encode(additionalCharges, forKey: .additionalCharges)
        try container.encode(grandTotal, forKey: .grandTotal)
        try container.encode(amountPaid, forKey: .amountPaid)
        try container.encode(orderAmountPending, forKey: .orderAmountPending)
        try container.encode(taxPercent, forKey: .taxPercent)
        try container.encode(discountPercent, forKey: .discountPercent)
        try container.encode(refundAmount, forKey: .refundAmount)
        try container.encodeIfPresent(refund, forKey: .refund)
        try container.encode(lastOrderPaymentStatusID, forKey: .lastOrderPaymentStatusID)
        try container.encode(isCompleted, forKey: .isCompleted)
        try container.encode(technicians, forKey: .technicians)
        try container.encode(lineItems, forKey: .lineItems)
        try container.encodeIfPresent(orderHistory, forKey: .orderHistory)
        try container.encode(orderNotes, forKey: .orderNotes)
        try container.encode(payments, forKey: .payments)
        try container.encodeIfPresent(car, forKey: .car)
        try container.encodeIfPresent(customer, forKey: .customer)
        try container.encodeIfPresent(companyClient, forKey: .companyClient)
        try container.encodeIfPresent(location, forKey: .location)
        try container.encodeIfPresent(zatcaStatus, forKey: .zatcaStatus)
        try container.encodeIfPresent(zatcaClearanceStatus, forKey: .zatcaClearanceStatus)
        try container.encodeIfPresent(zatcaInvoiceUUID, forKey: .zatcaInvoiceUUID)
        try container.encodeIfPresent(zatcaQRCode, forKey: .zatcaQRCode)
        try container.encodeIfPresent(zatcaSubmittedAt, forKey: .zatcaSubmittedAt)
        try container.encodeIfPresent(zatcaErrorMessage, forKey: .zatcaErrorMessage)
    }
}

