//
// PackageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PackageResponse: Sendable, Codable, Hashable {

    public var packageID: Int64
    public var categoryID: Int64
    public var name: String?
    public var nameAr: String?
    public var description: String?
    public var descriptionAr: String?
    public var price: Double
    public var cost: Double
    public var SKU: String?
    public var barcode: String?
    public var imagePath: String?
    public var accountID: Int64
    public var createdAt: Date?
    public var updatedAt: Date?
    public var statusID: StatusType
    public var categoryName: String?
    public var accountName: String?
    public var locationPackages: [LocationPackageResponse]
    public var packageDetails: [PackageDetailResponse]

    public init(packageID: Int64, categoryID: Int64, name: String? = nil, nameAr: String? = nil, description: String? = nil, descriptionAr: String? = nil, price: Double, cost: Double, SKU: String? = nil, barcode: String? = nil, imagePath: String? = nil, accountID: Int64, createdAt: Date? = nil, updatedAt: Date? = nil, statusID: StatusType, categoryName: String? = nil, accountName: String? = nil, locationPackages: [LocationPackageResponse], packageDetails: [PackageDetailResponse]) {
        self.packageID = packageID
        self.categoryID = categoryID
        self.name = name
        self.nameAr = nameAr
        self.description = description
        self.descriptionAr = descriptionAr
        self.price = price
        self.cost = cost
        self.SKU = SKU
        self.barcode = barcode
        self.imagePath = imagePath
        self.accountID = accountID
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.statusID = statusID
        self.categoryName = categoryName
        self.accountName = accountName
        self.locationPackages = locationPackages
        self.packageDetails = packageDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case packageID = "PackageID"
        case categoryID = "CategoryID"
        case name = "Name"
        case nameAr = "NameAr"
        case description = "Description"
        case descriptionAr = "DescriptionAr"
        case price = "Price"
        case cost = "Cost"
        case SKU
        case barcode = "Barcode"
        case imagePath = "ImagePath"
        case accountID = "AccountID"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case statusID = "StatusID"
        case categoryName = "CategoryName"
        case accountName = "AccountName"
        case locationPackages = "LocationPackages"
        case packageDetails = "PackageDetails"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(packageID, forKey: .packageID)
        try container.encode(categoryID, forKey: .categoryID)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(nameAr, forKey: .nameAr)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(descriptionAr, forKey: .descriptionAr)
        try container.encode(price, forKey: .price)
        try container.encode(cost, forKey: .cost)
        try container.encodeIfPresent(SKU, forKey: .SKU)
        try container.encodeIfPresent(barcode, forKey: .barcode)
        try container.encodeIfPresent(imagePath, forKey: .imagePath)
        try container.encode(accountID, forKey: .accountID)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encode(statusID, forKey: .statusID)
        try container.encodeIfPresent(categoryName, forKey: .categoryName)
        try container.encodeIfPresent(accountName, forKey: .accountName)
        try container.encode(locationPackages, forKey: .locationPackages)
        try container.encode(packageDetails, forKey: .packageDetails)
    }
}

