//
// PackageReportDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Individual package row in the report */
public struct PackageReportDto: Sendable, Codable, Hashable {

    /** Package ID */
    public var packageID: Int64
    /** Package SKU */
    public var SKU: String
    /** Package name */
    public var packageName: String
    /** Total quantity sold (minus refunded quantity) */
    public var packagesSold: Double
    /** Gross sales (Quantity × UnitPrice, before discounts) */
    public var grossSales: Double
    /** Net sales (Gross - Line Discounts - Allocated Order Discounts + Taxes) */
    public var netSales: Double
    /** Total refund amount for this package */
    public var refund: Double
    /** Total discount (line item discount + allocated order discount) */
    public var discount: Double
    /** Total tax amount */
    public var taxes: Double
    /** Package profit (Net Sales - Cost of Goods Sold) Calculated as: NetSales - (UnitCost × PackagesSold) */
    public var profit: Double

    public init(packageID: Int64, SKU: String, packageName: String, packagesSold: Double, grossSales: Double, netSales: Double, refund: Double, discount: Double, taxes: Double, profit: Double) {
        self.packageID = packageID
        self.SKU = SKU
        self.packageName = packageName
        self.packagesSold = packagesSold
        self.grossSales = grossSales
        self.netSales = netSales
        self.refund = refund
        self.discount = discount
        self.taxes = taxes
        self.profit = profit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case packageID = "PackageID"
        case SKU
        case packageName = "PackageName"
        case packagesSold = "PackagesSold"
        case grossSales = "GrossSales"
        case netSales = "NetSales"
        case refund = "Refund"
        case discount = "Discount"
        case taxes = "Taxes"
        case profit = "Profit"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(packageID, forKey: .packageID)
        try container.encode(SKU, forKey: .SKU)
        try container.encode(packageName, forKey: .packageName)
        try container.encode(packagesSold, forKey: .packagesSold)
        try container.encode(grossSales, forKey: .grossSales)
        try container.encode(netSales, forKey: .netSales)
        try container.encode(refund, forKey: .refund)
        try container.encode(discount, forKey: .discount)
        try container.encode(taxes, forKey: .taxes)
        try container.encode(profit, forKey: .profit)
    }
}

