//
// PagedResultOfWarehouseResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PagedResultOfWarehouseResponse: Sendable, Codable, Hashable {

    public var page: Int
    public var pageSize: Int
    public var totalCount: Int
    public var totalPages: Int
    public var data: [WarehouseResponse]

    public init(page: Int, pageSize: Int, totalCount: Int, totalPages: Int, data: [WarehouseResponse]) {
        self.page = page
        self.pageSize = pageSize
        self.totalCount = totalCount
        self.totalPages = totalPages
        self.data = data
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case page = "Page"
        case pageSize = "PageSize"
        case totalCount = "TotalCount"
        case totalPages = "TotalPages"
        case data = "Data"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(page, forKey: .page)
        try container.encode(pageSize, forKey: .pageSize)
        try container.encode(totalCount, forKey: .totalCount)
        try container.encode(totalPages, forKey: .totalPages)
        try container.encode(data, forKey: .data)
    }
}

