//
// PatchLineItemStatusRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PatchLineItemStatusRequest: Sendable, Codable, Hashable {

    public var lineItemID: Int64
    public var lineItemStatus: ServiceStatusType

    public init(lineItemID: Int64, lineItemStatus: ServiceStatusType) {
        self.lineItemID = lineItemID
        self.lineItemStatus = lineItemStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case lineItemID = "LineItemID"
        case lineItemStatus = "LineItemStatus"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(lineItemID, forKey: .lineItemID)
        try container.encode(lineItemStatus, forKey: .lineItemStatus)
    }
}

