//
// PatchOrderRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PatchOrderRequest: Sendable, Codable, Hashable {

    public var carID: Int64?
    public var customerID: Int64?
    public var bayID: Int64?
    public var lastServiceStatusID: ServiceStatusType?
    public var orderTakerID: Int64?
    public var locationID: Int64?
    public var orderType: OrderType?
    public var discountID: Int64?
    public var discountCode: String?
    public var technicians: [TechnicianRequest]?
    public var lineItemStatuses: [PatchLineItemStatusRequest]?
    public var subtotal: Double?
    public var discountAmount: Double?
    public var tax: Double?
    public var additionalCharges: Double?
    public var total: Double?
    public var amountPaid: Double?
    public var taxPercent: Double?
    public var discountPercent: Double?
    public var refundAmount: Double?
    public var lastOrderPaymentStatusID: OrderPaymentStatusType?

    public init(carID: Int64? = nil, customerID: Int64? = nil, bayID: Int64? = nil, lastServiceStatusID: ServiceStatusType? = nil, orderTakerID: Int64? = nil, locationID: Int64? = nil, orderType: OrderType? = nil, discountID: Int64? = nil, discountCode: String? = nil, technicians: [TechnicianRequest]? = nil, lineItemStatuses: [PatchLineItemStatusRequest]? = nil, subtotal: Double? = nil, discountAmount: Double? = nil, tax: Double? = nil, additionalCharges: Double? = nil, total: Double? = nil, amountPaid: Double? = nil, taxPercent: Double? = nil, discountPercent: Double? = nil, refundAmount: Double? = nil, lastOrderPaymentStatusID: OrderPaymentStatusType? = nil) {
        self.carID = carID
        self.customerID = customerID
        self.bayID = bayID
        self.lastServiceStatusID = lastServiceStatusID
        self.orderTakerID = orderTakerID
        self.locationID = locationID
        self.orderType = orderType
        self.discountID = discountID
        self.discountCode = discountCode
        self.technicians = technicians
        self.lineItemStatuses = lineItemStatuses
        self.subtotal = subtotal
        self.discountAmount = discountAmount
        self.tax = tax
        self.additionalCharges = additionalCharges
        self.total = total
        self.amountPaid = amountPaid
        self.taxPercent = taxPercent
        self.discountPercent = discountPercent
        self.refundAmount = refundAmount
        self.lastOrderPaymentStatusID = lastOrderPaymentStatusID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case carID = "CarID"
        case customerID = "CustomerID"
        case bayID = "BayID"
        case lastServiceStatusID = "LastServiceStatusID"
        case orderTakerID = "OrderTakerID"
        case locationID = "LocationID"
        case orderType = "OrderType"
        case discountID = "DiscountID"
        case discountCode = "DiscountCode"
        case technicians = "Technicians"
        case lineItemStatuses = "LineItemStatuses"
        case subtotal = "Subtotal"
        case discountAmount = "DiscountAmount"
        case tax = "Tax"
        case additionalCharges = "AdditionalCharges"
        case total = "Total"
        case amountPaid = "AmountPaid"
        case taxPercent = "TaxPercent"
        case discountPercent = "DiscountPercent"
        case refundAmount = "RefundAmount"
        case lastOrderPaymentStatusID = "LastOrderPaymentStatusID"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(carID, forKey: .carID)
        try container.encodeIfPresent(customerID, forKey: .customerID)
        try container.encodeIfPresent(bayID, forKey: .bayID)
        try container.encodeIfPresent(lastServiceStatusID, forKey: .lastServiceStatusID)
        try container.encodeIfPresent(orderTakerID, forKey: .orderTakerID)
        try container.encodeIfPresent(locationID, forKey: .locationID)
        try container.encodeIfPresent(orderType, forKey: .orderType)
        try container.encodeIfPresent(discountID, forKey: .discountID)
        try container.encodeIfPresent(discountCode, forKey: .discountCode)
        try container.encodeIfPresent(technicians, forKey: .technicians)
        try container.encodeIfPresent(lineItemStatuses, forKey: .lineItemStatuses)
        try container.encodeIfPresent(subtotal, forKey: .subtotal)
        try container.encodeIfPresent(discountAmount, forKey: .discountAmount)
        try container.encodeIfPresent(tax, forKey: .tax)
        try container.encodeIfPresent(additionalCharges, forKey: .additionalCharges)
        try container.encodeIfPresent(total, forKey: .total)
        try container.encodeIfPresent(amountPaid, forKey: .amountPaid)
        try container.encodeIfPresent(taxPercent, forKey: .taxPercent)
        try container.encodeIfPresent(discountPercent, forKey: .discountPercent)
        try container.encodeIfPresent(refundAmount, forKey: .refundAmount)
        try container.encodeIfPresent(lastOrderPaymentStatusID, forKey: .lastOrderPaymentStatusID)
    }
}

