//
// PaymentModeBreakdown.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Payment method breakdown showing amount and transaction count per payment mode */
public struct PaymentModeBreakdown: Sendable, Codable, Hashable {

    public var paymentModeName: String
    public var amount: Double
    public var transactionCount: Int
    public var refundAmount: Double

    public init(paymentModeName: String, amount: Double, transactionCount: Int, refundAmount: Double) {
        self.paymentModeName = paymentModeName
        self.amount = amount
        self.transactionCount = transactionCount
        self.refundAmount = refundAmount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case paymentModeName = "PaymentModeName"
        case amount = "Amount"
        case transactionCount = "TransactionCount"
        case refundAmount = "RefundAmount"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(paymentModeName, forKey: .paymentModeName)
        try container.encode(amount, forKey: .amount)
        try container.encode(transactionCount, forKey: .transactionCount)
        try container.encode(refundAmount, forKey: .refundAmount)
    }
}

