//
// PaymentRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PaymentRequest: Sendable, Codable, Hashable {

    public var notes: String?
    public var paymentModeID: Int64
    public var amountPaid: Double
    public var externalReferenceNumber: String?

    public init(notes: String? = nil, paymentModeID: Int64, amountPaid: Double, externalReferenceNumber: String? = nil) {
        self.notes = notes
        self.paymentModeID = paymentModeID
        self.amountPaid = amountPaid
        self.externalReferenceNumber = externalReferenceNumber
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case notes = "Notes"
        case paymentModeID = "PaymentModeID"
        case amountPaid = "AmountPaid"
        case externalReferenceNumber = "ExternalReferenceNumber"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encode(paymentModeID, forKey: .paymentModeID)
        try container.encode(amountPaid, forKey: .amountPaid)
        try container.encodeIfPresent(externalReferenceNumber, forKey: .externalReferenceNumber)
    }
}

