//
// PosSessionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Full response model for a POS session. */
public struct PosSessionResponse: Sendable, Codable, Hashable {

    /** Unique session identifier. */
    public var sessionID: Int64
    /** Auto-generated sequence number. */
    public var sessionNo: Int64
    /** Display name for the session. */
    public var name: String?
    public var state: PosSessionState
    /** Human-readable state name. */
    public var stateName: String
    /** Terminal ID this session belongs to. */
    public var terminalID: Int64
    /** Terminal name. */
    public var terminalName: String?
    /** Location ID where the session is operating. */
    public var locationID: Int64
    /** Location name. */
    public var locationName: String?
    /** User ID who opened the session. */
    public var openedByUserID: Int64
    /** Name of the user who opened the session. */
    public var openedByUserName: String?
    /** User ID who closed the session (null if not closed). */
    public var closedByUserID: Int64?
    /** Name of the user who closed the session. */
    public var closedByUserName: String?
    /** When the session was created. */
    public var createdAt: Date?
    /** When the session was opened (transitioned to Opened state). */
    public var openedAt: Date?
    /** When the session was closed (transitioned to Closed state). */
    public var closedAt: Date?
    /** Opening cash balance entered by user. */
    public var cashOpeningBalance: Double
    /** Calculated theoretical closing balance. */
    public var cashClosingBalanceTheoretical: Double
    /** Actual cash counted at closing. */
    public var cashClosingBalanceActual: Double
    /** Difference between actual and theoretical (positive = surplus, negative = shortage). */
    public var cashDifference: Double
    /** Total sales amount from all orders. */
    public var totalSales: Double
    /** Total refunds amount from all orders. */
    public var totalRefunds: Double
    /** Total cash payments received. */
    public var totalCashPayments: Double
    /** Total card payments received. */
    public var totalCardPayments: Double
    /** Total other payment types received. */
    public var totalOtherPayments: Double
    /** Number of orders processed in this session. */
    public var orderCount: Int
    /** Notes entered when opening the session. */
    public var openingNotes: String?
    /** Notes entered when closing the session. */
    public var closingNotes: String?

    public init(sessionID: Int64, sessionNo: Int64, name: String? = nil, state: PosSessionState, stateName: String, terminalID: Int64, terminalName: String? = nil, locationID: Int64, locationName: String? = nil, openedByUserID: Int64, openedByUserName: String? = nil, closedByUserID: Int64? = nil, closedByUserName: String? = nil, createdAt: Date? = nil, openedAt: Date? = nil, closedAt: Date? = nil, cashOpeningBalance: Double, cashClosingBalanceTheoretical: Double, cashClosingBalanceActual: Double, cashDifference: Double, totalSales: Double, totalRefunds: Double, totalCashPayments: Double, totalCardPayments: Double, totalOtherPayments: Double, orderCount: Int, openingNotes: String? = nil, closingNotes: String? = nil) {
        self.sessionID = sessionID
        self.sessionNo = sessionNo
        self.name = name
        self.state = state
        self.stateName = stateName
        self.terminalID = terminalID
        self.terminalName = terminalName
        self.locationID = locationID
        self.locationName = locationName
        self.openedByUserID = openedByUserID
        self.openedByUserName = openedByUserName
        self.closedByUserID = closedByUserID
        self.closedByUserName = closedByUserName
        self.createdAt = createdAt
        self.openedAt = openedAt
        self.closedAt = closedAt
        self.cashOpeningBalance = cashOpeningBalance
        self.cashClosingBalanceTheoretical = cashClosingBalanceTheoretical
        self.cashClosingBalanceActual = cashClosingBalanceActual
        self.cashDifference = cashDifference
        self.totalSales = totalSales
        self.totalRefunds = totalRefunds
        self.totalCashPayments = totalCashPayments
        self.totalCardPayments = totalCardPayments
        self.totalOtherPayments = totalOtherPayments
        self.orderCount = orderCount
        self.openingNotes = openingNotes
        self.closingNotes = closingNotes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sessionID = "SessionID"
        case sessionNo = "SessionNo"
        case name = "Name"
        case state = "State"
        case stateName = "StateName"
        case terminalID = "TerminalID"
        case terminalName = "TerminalName"
        case locationID = "LocationID"
        case locationName = "LocationName"
        case openedByUserID = "OpenedByUserID"
        case openedByUserName = "OpenedByUserName"
        case closedByUserID = "ClosedByUserID"
        case closedByUserName = "ClosedByUserName"
        case createdAt = "CreatedAt"
        case openedAt = "OpenedAt"
        case closedAt = "ClosedAt"
        case cashOpeningBalance = "CashOpeningBalance"
        case cashClosingBalanceTheoretical = "CashClosingBalanceTheoretical"
        case cashClosingBalanceActual = "CashClosingBalanceActual"
        case cashDifference = "CashDifference"
        case totalSales = "TotalSales"
        case totalRefunds = "TotalRefunds"
        case totalCashPayments = "TotalCashPayments"
        case totalCardPayments = "TotalCardPayments"
        case totalOtherPayments = "TotalOtherPayments"
        case orderCount = "OrderCount"
        case openingNotes = "OpeningNotes"
        case closingNotes = "ClosingNotes"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sessionID, forKey: .sessionID)
        try container.encode(sessionNo, forKey: .sessionNo)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encode(state, forKey: .state)
        try container.encode(stateName, forKey: .stateName)
        try container.encode(terminalID, forKey: .terminalID)
        try container.encodeIfPresent(terminalName, forKey: .terminalName)
        try container.encode(locationID, forKey: .locationID)
        try container.encodeIfPresent(locationName, forKey: .locationName)
        try container.encode(openedByUserID, forKey: .openedByUserID)
        try container.encodeIfPresent(openedByUserName, forKey: .openedByUserName)
        try container.encodeIfPresent(closedByUserID, forKey: .closedByUserID)
        try container.encodeIfPresent(closedByUserName, forKey: .closedByUserName)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(openedAt, forKey: .openedAt)
        try container.encodeIfPresent(closedAt, forKey: .closedAt)
        try container.encode(cashOpeningBalance, forKey: .cashOpeningBalance)
        try container.encode(cashClosingBalanceTheoretical, forKey: .cashClosingBalanceTheoretical)
        try container.encode(cashClosingBalanceActual, forKey: .cashClosingBalanceActual)
        try container.encode(cashDifference, forKey: .cashDifference)
        try container.encode(totalSales, forKey: .totalSales)
        try container.encode(totalRefunds, forKey: .totalRefunds)
        try container.encode(totalCashPayments, forKey: .totalCashPayments)
        try container.encode(totalCardPayments, forKey: .totalCardPayments)
        try container.encode(totalOtherPayments, forKey: .totalOtherPayments)
        try container.encode(orderCount, forKey: .orderCount)
        try container.encodeIfPresent(openingNotes, forKey: .openingNotes)
        try container.encodeIfPresent(closingNotes, forKey: .closingNotes)
    }
}

