//
// PurchaseBillStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum PurchaseBillStatus: Int, Sendable, Codable, CaseIterable {
    case Pending = 1
    case Cancelled = 2
    case Posted = 3
}
