//
// PurchaseBillPaymentStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum PurchaseBillPaymentStatus: Int, Sendable, Codable, CaseIterable {
    case Unpaid = 1
    case Paid = 2
}
