//
// ReceiptSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ReceiptSettings: Sendable, Codable, Hashable {

    public var hasLogo: Bool
    public var hasLocationAddress: Bool
    public var hasPhoneNo: Bool
    public var hasVatNo: Bool
    public var hasCashierName: Bool
    public var hasBayName: Bool
    public var hasKilometers: Bool
    public var hasNotes: Bool
    public var hasSocialMedia: Bool
    public var showCustomerName: Bool
    public var showOrderName: Bool
    public var showCRNo: Bool

    public init(hasLogo: Bool, hasLocationAddress: Bool, hasPhoneNo: Bool, hasVatNo: Bool, hasCashierName: Bool, hasBayName: Bool, hasKilometers: Bool, hasNotes: Bool, hasSocialMedia: Bool, showCustomerName: Bool, showOrderName: Bool, showCRNo: Bool) {
        self.hasLogo = hasLogo
        self.hasLocationAddress = hasLocationAddress
        self.hasPhoneNo = hasPhoneNo
        self.hasVatNo = hasVatNo
        self.hasCashierName = hasCashierName
        self.hasBayName = hasBayName
        self.hasKilometers = hasKilometers
        self.hasNotes = hasNotes
        self.hasSocialMedia = hasSocialMedia
        self.showCustomerName = showCustomerName
        self.showOrderName = showOrderName
        self.showCRNo = showCRNo
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hasLogo = "HasLogo"
        case hasLocationAddress = "HasLocationAddress"
        case hasPhoneNo = "HasPhoneNo"
        case hasVatNo = "HasVatNo"
        case hasCashierName = "HasCashierName"
        case hasBayName = "HasBayName"
        case hasKilometers = "HasKilometers"
        case hasNotes = "HasNotes"
        case hasSocialMedia = "HasSocialMedia"
        case showCustomerName = "ShowCustomerName"
        case showOrderName = "ShowOrderName"
        case showCRNo = "ShowCRNo"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(hasLogo, forKey: .hasLogo)
        try container.encode(hasLocationAddress, forKey: .hasLocationAddress)
        try container.encode(hasPhoneNo, forKey: .hasPhoneNo)
        try container.encode(hasVatNo, forKey: .hasVatNo)
        try container.encode(hasCashierName, forKey: .hasCashierName)
        try container.encode(hasBayName, forKey: .hasBayName)
        try container.encode(hasKilometers, forKey: .hasKilometers)
        try container.encode(hasNotes, forKey: .hasNotes)
        try container.encode(hasSocialMedia, forKey: .hasSocialMedia)
        try container.encode(showCustomerName, forKey: .showCustomerName)
        try container.encode(showOrderName, forKey: .showOrderName)
        try container.encode(showCRNo, forKey: .showCRNo)
    }
}

