//
// ReconciliationDetailResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ReconciliationDetailResponse: Sendable, Codable, Hashable {

    public var reconciliationDetailID: Int64
    public var reconciliationID: Int64
    public var itemID: Int64
    public var itemName: String?
    public var systemQuantity: Double
    public var physicalQuantity: Double
    public var variance: Double
    public var variancePercentage: Double?
    public var unitID: Int64?
    public var unitName: String?
    public var reasonType: ReconciliationVarianceReason?
    public var notes: String?
    public var isApproved: Bool?
    public var statusID: StatusType
    public var createdAt: Date?
    public var updatedAt: Date?

    public init(reconciliationDetailID: Int64, reconciliationID: Int64, itemID: Int64, itemName: String? = nil, systemQuantity: Double, physicalQuantity: Double, variance: Double, variancePercentage: Double? = nil, unitID: Int64? = nil, unitName: String? = nil, reasonType: ReconciliationVarianceReason? = nil, notes: String? = nil, isApproved: Bool? = nil, statusID: StatusType, createdAt: Date? = nil, updatedAt: Date? = nil) {
        self.reconciliationDetailID = reconciliationDetailID
        self.reconciliationID = reconciliationID
        self.itemID = itemID
        self.itemName = itemName
        self.systemQuantity = systemQuantity
        self.physicalQuantity = physicalQuantity
        self.variance = variance
        self.variancePercentage = variancePercentage
        self.unitID = unitID
        self.unitName = unitName
        self.reasonType = reasonType
        self.notes = notes
        self.isApproved = isApproved
        self.statusID = statusID
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reconciliationDetailID = "ReconciliationDetailID"
        case reconciliationID = "ReconciliationID"
        case itemID = "ItemID"
        case itemName = "ItemName"
        case systemQuantity = "SystemQuantity"
        case physicalQuantity = "PhysicalQuantity"
        case variance = "Variance"
        case variancePercentage = "VariancePercentage"
        case unitID = "UnitID"
        case unitName = "UnitName"
        case reasonType = "ReasonType"
        case notes = "Notes"
        case isApproved = "IsApproved"
        case statusID = "StatusID"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(reconciliationDetailID, forKey: .reconciliationDetailID)
        try container.encode(reconciliationID, forKey: .reconciliationID)
        try container.encode(itemID, forKey: .itemID)
        try container.encodeIfPresent(itemName, forKey: .itemName)
        try container.encode(systemQuantity, forKey: .systemQuantity)
        try container.encode(physicalQuantity, forKey: .physicalQuantity)
        try container.encode(variance, forKey: .variance)
        try container.encodeIfPresent(variancePercentage, forKey: .variancePercentage)
        try container.encodeIfPresent(unitID, forKey: .unitID)
        try container.encodeIfPresent(unitName, forKey: .unitName)
        try container.encodeIfPresent(reasonType, forKey: .reasonType)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(isApproved, forKey: .isApproved)
        try container.encode(statusID, forKey: .statusID)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
    }
}

