//
// ReconciliationRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ReconciliationRequest: Sendable, Codable, Hashable {

    public static let warehouseIDRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: true, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var warehouseID: Int64
    public var reconciliationType: ReconciliationType
    public var reconciliationDate: Date?
    public var notes: String?
    public var reasonType: ReconciliationVarianceReason?
    public var attachments: [String]
    public var details: [ReconciliationDetailRequest]

    public init(warehouseID: Int64, reconciliationType: ReconciliationType, reconciliationDate: Date? = nil, notes: String? = nil, reasonType: ReconciliationVarianceReason? = nil, attachments: [String], details: [ReconciliationDetailRequest]) {
        self.warehouseID = warehouseID
        self.reconciliationType = reconciliationType
        self.reconciliationDate = reconciliationDate
        self.notes = notes
        self.reasonType = reasonType
        self.attachments = attachments
        self.details = details
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case warehouseID = "WarehouseID"
        case reconciliationType = "ReconciliationType"
        case reconciliationDate = "ReconciliationDate"
        case notes = "Notes"
        case reasonType = "ReasonType"
        case attachments = "Attachments"
        case details = "Details"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(warehouseID, forKey: .warehouseID)
        try container.encode(reconciliationType, forKey: .reconciliationType)
        try container.encodeIfPresent(reconciliationDate, forKey: .reconciliationDate)
        try container.encodeIfPresent(notes, forKey: .notes)
        try container.encodeIfPresent(reasonType, forKey: .reasonType)
        try container.encode(attachments, forKey: .attachments)
        try container.encode(details, forKey: .details)
    }
}

