//
// ReconciliationPhysicalDetailRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ReconciliationPhysicalDetailRequest: Sendable, Codable, Hashable {

    public static let itemIDRule = NumericRule<Int64>(minimum: 0, exclusiveMinimum: true, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let physicalQuantityRule = NumericRule<Double>(minimum: 0.0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var itemID: Int64
    public var physicalQuantity: Double
    public var reasonType: ReconciliationVarianceReason?
    public var notes: String?

    public init(itemID: Int64, physicalQuantity: Double, reasonType: ReconciliationVarianceReason? = nil, notes: String? = nil) {
        self.itemID = itemID
        self.physicalQuantity = physicalQuantity
        self.reasonType = reasonType
        self.notes = notes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case itemID = "ItemID"
        case physicalQuantity = "PhysicalQuantity"
        case reasonType = "ReasonType"
        case notes = "Notes"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(itemID, forKey: .itemID)
        try container.encode(physicalQuantity, forKey: .physicalQuantity)
        try container.encodeIfPresent(reasonType, forKey: .reasonType)
        try container.encodeIfPresent(notes, forKey: .notes)
    }
}

