//
// ReconciliationStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ReconciliationStatus: Int, Sendable, Codable, CaseIterable {
    case Draft = 701
    case InProgress = 702
    case AuditPending = 703
    case Approved = 704
    case Rejected = 705
    case Cancelled = 706
    case PartiallyApproved = 707
}
