//
// RefundDiscountAccountingPolicy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum RefundDiscountAccountingPolicy: Int, Sendable, Codable, CaseIterable {
    case ProportionalDiscount = 0
    case FullRefundOnly = 1
}
