//
// RefundReasonItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Refund reason with amount */
public struct RefundReasonItem: Sendable, Codable, Hashable {

    /** Refund reason text */
    public var reason: String
    /** Number of refunds with this reason */
    public var count: Int
    /** Total refund amount for this reason */
    public var amount: Double
    /** Percentage of total refunds */
    public var percentage: Double

    public init(reason: String, count: Int, amount: Double, percentage: Double) {
        self.reason = reason
        self.count = count
        self.amount = amount
        self.percentage = percentage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case reason = "Reason"
        case count = "Count"
        case amount = "Amount"
        case percentage = "Percentage"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(reason, forKey: .reason)
        try container.encode(count, forKey: .count)
        try container.encode(amount, forKey: .amount)
        try container.encode(percentage, forKey: .percentage)
    }
}

