//
// RefundSummaryRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RefundSummaryRequest: Sendable, Codable, Hashable {

    public static let totalRefundAmountRule = NumericRule<Double>(minimum: 0.0, exclusiveMinimum: true, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let totalRefundTaxRule = NumericRule<Double>(minimum: 0.0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let grandTotalRefundRule = NumericRule<Double>(minimum: 0.0, exclusiveMinimum: true, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var totalRefundAmount: Double
    public var totalRefundTax: Double
    public var grandTotalRefund: Double
    public var refundDate: Date?

    public init(totalRefundAmount: Double, totalRefundTax: Double, grandTotalRefund: Double, refundDate: Date? = nil) {
        self.totalRefundAmount = totalRefundAmount
        self.totalRefundTax = totalRefundTax
        self.grandTotalRefund = grandTotalRefund
        self.refundDate = refundDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalRefundAmount = "TotalRefundAmount"
        case totalRefundTax = "TotalRefundTax"
        case grandTotalRefund = "GrandTotalRefund"
        case refundDate = "RefundDate"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(totalRefundAmount, forKey: .totalRefundAmount)
        try container.encode(totalRefundTax, forKey: .totalRefundTax)
        try container.encode(grandTotalRefund, forKey: .grandTotalRefund)
        try container.encodeIfPresent(refundDate, forKey: .refundDate)
    }
}

