//
// RefundPolicyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RefundPolicyResponse: Sendable, Codable, Hashable {

    public var refundPolicyID: Int64
    public var accountID: Int64
    public var accountName: String
    public var locationID: Int64?
    public var locationName: String?
    public var policyType: RefundDiscountAccountingPolicy
    public var policyTypeName: String
    public var allowFreeItemProportionalRefund: Bool
    public var createdAt: Date?
    public var updatedAt: Date?
    public var createdBy: Int64?
    public var lastUpdatedBy: Int64?

    public init(refundPolicyID: Int64, accountID: Int64, accountName: String, locationID: Int64? = nil, locationName: String? = nil, policyType: RefundDiscountAccountingPolicy, policyTypeName: String, allowFreeItemProportionalRefund: Bool, createdAt: Date? = nil, updatedAt: Date? = nil, createdBy: Int64? = nil, lastUpdatedBy: Int64? = nil) {
        self.refundPolicyID = refundPolicyID
        self.accountID = accountID
        self.accountName = accountName
        self.locationID = locationID
        self.locationName = locationName
        self.policyType = policyType
        self.policyTypeName = policyTypeName
        self.allowFreeItemProportionalRefund = allowFreeItemProportionalRefund
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.createdBy = createdBy
        self.lastUpdatedBy = lastUpdatedBy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case refundPolicyID = "RefundPolicyID"
        case accountID = "AccountID"
        case accountName = "AccountName"
        case locationID = "LocationID"
        case locationName = "LocationName"
        case policyType = "PolicyType"
        case policyTypeName = "PolicyTypeName"
        case allowFreeItemProportionalRefund = "AllowFreeItemProportionalRefund"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case createdBy = "CreatedBy"
        case lastUpdatedBy = "LastUpdatedBy"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(refundPolicyID, forKey: .refundPolicyID)
        try container.encode(accountID, forKey: .accountID)
        try container.encode(accountName, forKey: .accountName)
        try container.encodeIfPresent(locationID, forKey: .locationID)
        try container.encodeIfPresent(locationName, forKey: .locationName)
        try container.encode(policyType, forKey: .policyType)
        try container.encode(policyTypeName, forKey: .policyTypeName)
        try container.encode(allowFreeItemProportionalRefund, forKey: .allowFreeItemProportionalRefund)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encodeIfPresent(createdBy, forKey: .createdBy)
        try container.encodeIfPresent(lastUpdatedBy, forKey: .lastUpdatedBy)
    }
}

