//
// ReportResultOfNoRowDataAndOverviewReportSummary.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Container for report results with data rows and summary */
public struct ReportResultOfNoRowDataAndOverviewReportSummary: Sendable, Codable, Hashable {

    public var rows: PagedResultOfNoRowData
    public var summary: OverviewReportSummary?

    public init(rows: PagedResultOfNoRowData, summary: OverviewReportSummary? = nil) {
        self.rows = rows
        self.summary = summary
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case rows = "Rows"
        case summary = "Summary"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(rows, forKey: .rows)
        try container.encodeIfPresent(summary, forKey: .summary)
    }
}

