//
// ServiceRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ServiceRequest: Sendable, Codable, Hashable {

    public static let nameRule = StringRule(minLength: 0, maxLength: 200, pattern: nil)
    public static let descriptionArRule = StringRule(minLength: 0, maxLength: 500, pattern: nil)
    public static let displayOrderRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public static let statusIDRule = NumericRule<Int>(minimum: nil, exclusiveMinimum: false, maximum: nil, exclusiveMaximum: false, multipleOf: nil)
    public var name: String
    public var nameAr: String?
    public var description: String?
    public var descriptionAr: String?
    public var imagePath: String?
    public var displayOrder: Int?
    public var businessService: [String]?
    public var statusID: Int

    public init(name: String, nameAr: String? = nil, description: String? = nil, descriptionAr: String? = nil, imagePath: String? = nil, displayOrder: Int? = nil, businessService: [String]? = nil, statusID: Int) {
        self.name = name
        self.nameAr = nameAr
        self.description = description
        self.descriptionAr = descriptionAr
        self.imagePath = imagePath
        self.displayOrder = displayOrder
        self.businessService = businessService
        self.statusID = statusID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name = "Name"
        case nameAr = "NameAr"
        case description = "Description"
        case descriptionAr = "DescriptionAr"
        case imagePath = "ImagePath"
        case displayOrder = "DisplayOrder"
        case businessService = "BusinessService"
        case statusID = "StatusID"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(nameAr, forKey: .nameAr)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(descriptionAr, forKey: .descriptionAr)
        try container.encodeIfPresent(imagePath, forKey: .imagePath)
        try container.encodeIfPresent(displayOrder, forKey: .displayOrder)
        try container.encodeIfPresent(businessService, forKey: .businessService)
        try container.encode(statusID, forKey: .statusID)
    }
}

