//
// ServiceStatusType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum ServiceStatusType: Int, Sendable, Codable, CaseIterable {
    case Lite = 100
    case Unassigned = 101
    case Assigned = 102
    case UnderService = 103
    case Paused = 104
    case ServiceFinished = 105
}
