//
// StockTransferResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct StockTransferResponse: Sendable, Codable, Hashable {

    public var transferID: Int64
    public var sourceWarehouseID: Int64
    public var sourceWarehouseName: String?
    public var destinationWarehouseID: Int64
    public var destinationWarehouseName: String?
    public var referenceNumber: String?
    public var priority: TransferPriority?
    public var urgencyReason: String?
    public var reason: TransferReason?
    public var otherReasonDescription: String?
    public var transportMethod: TransportMethod?
    public var shippingCost: Double?
    public var expectedDeliveryDate: Date?
    public var trackingNumber: String?
    public var transferDate: Date?
    public var requestedDate: Date?
    public var approvedDate: Date?
    public var receivedDate: Date?
    public var requestedByUserID: Int64?
    public var approvedByUserID: Int64?
    public var receivedByUserID: Int64?
    public var statusID: StockTransferStatus
    public var requestNotes: String?
    public var transferNotes: String?
    public var receiveNotes: String?
    public var rejectionReason: String?
    public var createdAt: Date?
    public var updatedAt: Date?
    public var items: [StockTransferDetailResponse]

    public init(transferID: Int64, sourceWarehouseID: Int64, sourceWarehouseName: String? = nil, destinationWarehouseID: Int64, destinationWarehouseName: String? = nil, referenceNumber: String? = nil, priority: TransferPriority? = nil, urgencyReason: String? = nil, reason: TransferReason? = nil, otherReasonDescription: String? = nil, transportMethod: TransportMethod? = nil, shippingCost: Double? = nil, expectedDeliveryDate: Date? = nil, trackingNumber: String? = nil, transferDate: Date? = nil, requestedDate: Date? = nil, approvedDate: Date? = nil, receivedDate: Date? = nil, requestedByUserID: Int64? = nil, approvedByUserID: Int64? = nil, receivedByUserID: Int64? = nil, statusID: StockTransferStatus, requestNotes: String? = nil, transferNotes: String? = nil, receiveNotes: String? = nil, rejectionReason: String? = nil, createdAt: Date? = nil, updatedAt: Date? = nil, items: [StockTransferDetailResponse]) {
        self.transferID = transferID
        self.sourceWarehouseID = sourceWarehouseID
        self.sourceWarehouseName = sourceWarehouseName
        self.destinationWarehouseID = destinationWarehouseID
        self.destinationWarehouseName = destinationWarehouseName
        self.referenceNumber = referenceNumber
        self.priority = priority
        self.urgencyReason = urgencyReason
        self.reason = reason
        self.otherReasonDescription = otherReasonDescription
        self.transportMethod = transportMethod
        self.shippingCost = shippingCost
        self.expectedDeliveryDate = expectedDeliveryDate
        self.trackingNumber = trackingNumber
        self.transferDate = transferDate
        self.requestedDate = requestedDate
        self.approvedDate = approvedDate
        self.receivedDate = receivedDate
        self.requestedByUserID = requestedByUserID
        self.approvedByUserID = approvedByUserID
        self.receivedByUserID = receivedByUserID
        self.statusID = statusID
        self.requestNotes = requestNotes
        self.transferNotes = transferNotes
        self.receiveNotes = receiveNotes
        self.rejectionReason = rejectionReason
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case transferID = "TransferID"
        case sourceWarehouseID = "SourceWarehouseID"
        case sourceWarehouseName = "SourceWarehouseName"
        case destinationWarehouseID = "DestinationWarehouseID"
        case destinationWarehouseName = "DestinationWarehouseName"
        case referenceNumber = "ReferenceNumber"
        case priority = "Priority"
        case urgencyReason = "UrgencyReason"
        case reason = "Reason"
        case otherReasonDescription = "OtherReasonDescription"
        case transportMethod = "TransportMethod"
        case shippingCost = "ShippingCost"
        case expectedDeliveryDate = "ExpectedDeliveryDate"
        case trackingNumber = "TrackingNumber"
        case transferDate = "TransferDate"
        case requestedDate = "RequestedDate"
        case approvedDate = "ApprovedDate"
        case receivedDate = "ReceivedDate"
        case requestedByUserID = "RequestedByUserID"
        case approvedByUserID = "ApprovedByUserID"
        case receivedByUserID = "ReceivedByUserID"
        case statusID = "StatusID"
        case requestNotes = "RequestNotes"
        case transferNotes = "TransferNotes"
        case receiveNotes = "ReceiveNotes"
        case rejectionReason = "RejectionReason"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case items = "Items"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(transferID, forKey: .transferID)
        try container.encode(sourceWarehouseID, forKey: .sourceWarehouseID)
        try container.encodeIfPresent(sourceWarehouseName, forKey: .sourceWarehouseName)
        try container.encode(destinationWarehouseID, forKey: .destinationWarehouseID)
        try container.encodeIfPresent(destinationWarehouseName, forKey: .destinationWarehouseName)
        try container.encodeIfPresent(referenceNumber, forKey: .referenceNumber)
        try container.encodeIfPresent(priority, forKey: .priority)
        try container.encodeIfPresent(urgencyReason, forKey: .urgencyReason)
        try container.encodeIfPresent(reason, forKey: .reason)
        try container.encodeIfPresent(otherReasonDescription, forKey: .otherReasonDescription)
        try container.encodeIfPresent(transportMethod, forKey: .transportMethod)
        try container.encodeIfPresent(shippingCost, forKey: .shippingCost)
        try container.encodeIfPresent(expectedDeliveryDate, forKey: .expectedDeliveryDate)
        try container.encodeIfPresent(trackingNumber, forKey: .trackingNumber)
        try container.encodeIfPresent(transferDate, forKey: .transferDate)
        try container.encodeIfPresent(requestedDate, forKey: .requestedDate)
        try container.encodeIfPresent(approvedDate, forKey: .approvedDate)
        try container.encodeIfPresent(receivedDate, forKey: .receivedDate)
        try container.encodeIfPresent(requestedByUserID, forKey: .requestedByUserID)
        try container.encodeIfPresent(approvedByUserID, forKey: .approvedByUserID)
        try container.encodeIfPresent(receivedByUserID, forKey: .receivedByUserID)
        try container.encode(statusID, forKey: .statusID)
        try container.encodeIfPresent(requestNotes, forKey: .requestNotes)
        try container.encodeIfPresent(transferNotes, forKey: .transferNotes)
        try container.encodeIfPresent(receiveNotes, forKey: .receiveNotes)
        try container.encodeIfPresent(rejectionReason, forKey: .rejectionReason)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encode(items, forKey: .items)
    }
}

