//
// SubscriptionType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum SubscriptionType: String, Sendable, Codable, CaseIterable {
    case Monthly = "Monthly"
    case Yearly = "Yearly"
}
