//
// SubscriptionDetailResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SubscriptionDetailResponse: Sendable, Codable, Hashable {

    public var subscriptionID: Int64
    public var CRMID: String?
    public var subscriptionName: String?
    public var accountID: Int64
    public var subscriptionType: SubscriptionType
    public var startDate: Date
    public var expiryDate: Date
    public var numberOfTerminals: Int
    public var paymentTerm: Int
    public var createdAt: Date?
    public var updatedAt: Date?
    public var statusID: StatusType
    public var accountName: String?
    public var activeTerminalsCount: Int
    public var terminals: [TerminalSummaryDto]
    public var addOns: [AddOnSummaryDto]

    public init(subscriptionID: Int64, CRMID: String? = nil, subscriptionName: String? = nil, accountID: Int64, subscriptionType: SubscriptionType, startDate: Date, expiryDate: Date, numberOfTerminals: Int, paymentTerm: Int, createdAt: Date? = nil, updatedAt: Date? = nil, statusID: StatusType, accountName: String? = nil, activeTerminalsCount: Int, terminals: [TerminalSummaryDto], addOns: [AddOnSummaryDto]) {
        self.subscriptionID = subscriptionID
        self.CRMID = CRMID
        self.subscriptionName = subscriptionName
        self.accountID = accountID
        self.subscriptionType = subscriptionType
        self.startDate = startDate
        self.expiryDate = expiryDate
        self.numberOfTerminals = numberOfTerminals
        self.paymentTerm = paymentTerm
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.statusID = statusID
        self.accountName = accountName
        self.activeTerminalsCount = activeTerminalsCount
        self.terminals = terminals
        self.addOns = addOns
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case subscriptionID = "SubscriptionID"
        case CRMID
        case subscriptionName = "SubscriptionName"
        case accountID = "AccountID"
        case subscriptionType = "SubscriptionType"
        case startDate = "StartDate"
        case expiryDate = "ExpiryDate"
        case numberOfTerminals = "NumberOfTerminals"
        case paymentTerm = "PaymentTerm"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case statusID = "StatusID"
        case accountName = "AccountName"
        case activeTerminalsCount = "ActiveTerminalsCount"
        case terminals = "Terminals"
        case addOns = "AddOns"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(subscriptionID, forKey: .subscriptionID)
        try container.encodeIfPresent(CRMID, forKey: .CRMID)
        try container.encodeIfPresent(subscriptionName, forKey: .subscriptionName)
        try container.encode(accountID, forKey: .accountID)
        try container.encode(subscriptionType, forKey: .subscriptionType)
        try container.encode(startDate, forKey: .startDate)
        try container.encode(expiryDate, forKey: .expiryDate)
        try container.encode(numberOfTerminals, forKey: .numberOfTerminals)
        try container.encode(paymentTerm, forKey: .paymentTerm)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encode(statusID, forKey: .statusID)
        try container.encodeIfPresent(accountName, forKey: .accountName)
        try container.encode(activeTerminalsCount, forKey: .activeTerminalsCount)
        try container.encode(terminals, forKey: .terminals)
        try container.encode(addOns, forKey: .addOns)
    }
}

