//
// SupplierPaymentTerms.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum SupplierPaymentTerms: Int, Sendable, Codable, CaseIterable {
    case COD = 1
    case Net7 = 2
    case Net15 = 3
    case Net30 = 4
    case Net60 = 5
    case Custom = 6
}
