//
// SystemComplianceResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Response for system compliance certificate creation. */
public struct SystemComplianceResponse: Sendable, Codable, Hashable {

    /** System compliance ID. */
    public var systemComplianceID: Int64
    /** Current certificate status. */
    public var certificateStatus: String
    /** Device name (usually \"Karage Server\"). */
    public var deviceName: String
    /** Certificate version. */
    public var version: Int
    /** When the certificate was created. */
    public var createdAt: Date?
    /** When the certificate expires. */
    public var expiresAt: Date?
    /** ZATCA Request ID. */
    public var requestID: String?

    public init(systemComplianceID: Int64, certificateStatus: String, deviceName: String, version: Int, createdAt: Date? = nil, expiresAt: Date? = nil, requestID: String? = nil) {
        self.systemComplianceID = systemComplianceID
        self.certificateStatus = certificateStatus
        self.deviceName = deviceName
        self.version = version
        self.createdAt = createdAt
        self.expiresAt = expiresAt
        self.requestID = requestID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case systemComplianceID = "SystemComplianceID"
        case certificateStatus = "CertificateStatus"
        case deviceName = "DeviceName"
        case version = "Version"
        case createdAt = "CreatedAt"
        case expiresAt = "ExpiresAt"
        case requestID = "RequestID"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(systemComplianceID, forKey: .systemComplianceID)
        try container.encode(certificateStatus, forKey: .certificateStatus)
        try container.encode(deviceName, forKey: .deviceName)
        try container.encode(version, forKey: .version)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(requestID, forKey: .requestID)
    }
}

