//
// TerminalSummaryDto.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TerminalSummaryDto: Sendable, Codable, Hashable {

    public var terminalID: Int64
    public var terminalName: String?
    public var devicePlatform: String?
    public var activationDate: Date?
    public var statusID: StatusType

    public init(terminalID: Int64, terminalName: String? = nil, devicePlatform: String? = nil, activationDate: Date? = nil, statusID: StatusType) {
        self.terminalID = terminalID
        self.terminalName = terminalName
        self.devicePlatform = devicePlatform
        self.activationDate = activationDate
        self.statusID = statusID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case terminalID = "TerminalID"
        case terminalName = "TerminalName"
        case devicePlatform = "DevicePlatform"
        case activationDate = "ActivationDate"
        case statusID = "StatusID"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(terminalID, forKey: .terminalID)
        try container.encodeIfPresent(terminalName, forKey: .terminalName)
        try container.encodeIfPresent(devicePlatform, forKey: .devicePlatform)
        try container.encodeIfPresent(activationDate, forKey: .activationDate)
        try container.encode(statusID, forKey: .statusID)
    }
}

