//
// TerminalReport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Per-terminal breakdown within a Z Report: aggregated totals + individual session reports */
public struct TerminalReport: Sendable, Codable, Hashable {

    public var terminalID: Int64
    public var terminalName: String
    public var sessions: [PosSessionReport]
    public var grossSales: Double
    public var totalDiscounts: Double
    public var totalRefunds: Double
    public var netSales: Double
    public var totalTax: Double
    public var voidedOrdersCount: Int
    public var voidedAmount: Double
    public var totalOrders: Int
    public var partialPaymentsCount: Int
    public var partialPaymentsAmount: Double
    public var refundedOrdersCount: Int
    public var paymentBreakdown: [PaymentModeBreakdown]
    public var cashOpeningBalance: Double
    public var cashPayments: Double
    public var cashRefunds: Double
    public var cashClosingBalanceExpected: Double
    public var cashClosingBalanceActual: Double
    public var cashDifference: Double

    public init(terminalID: Int64, terminalName: String, sessions: [PosSessionReport], grossSales: Double, totalDiscounts: Double, totalRefunds: Double, netSales: Double, totalTax: Double, voidedOrdersCount: Int, voidedAmount: Double, totalOrders: Int, partialPaymentsCount: Int, partialPaymentsAmount: Double, refundedOrdersCount: Int, paymentBreakdown: [PaymentModeBreakdown], cashOpeningBalance: Double, cashPayments: Double, cashRefunds: Double, cashClosingBalanceExpected: Double, cashClosingBalanceActual: Double, cashDifference: Double) {
        self.terminalID = terminalID
        self.terminalName = terminalName
        self.sessions = sessions
        self.grossSales = grossSales
        self.totalDiscounts = totalDiscounts
        self.totalRefunds = totalRefunds
        self.netSales = netSales
        self.totalTax = totalTax
        self.voidedOrdersCount = voidedOrdersCount
        self.voidedAmount = voidedAmount
        self.totalOrders = totalOrders
        self.partialPaymentsCount = partialPaymentsCount
        self.partialPaymentsAmount = partialPaymentsAmount
        self.refundedOrdersCount = refundedOrdersCount
        self.paymentBreakdown = paymentBreakdown
        self.cashOpeningBalance = cashOpeningBalance
        self.cashPayments = cashPayments
        self.cashRefunds = cashRefunds
        self.cashClosingBalanceExpected = cashClosingBalanceExpected
        self.cashClosingBalanceActual = cashClosingBalanceActual
        self.cashDifference = cashDifference
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case terminalID = "TerminalID"
        case terminalName = "TerminalName"
        case sessions = "Sessions"
        case grossSales = "GrossSales"
        case totalDiscounts = "TotalDiscounts"
        case totalRefunds = "TotalRefunds"
        case netSales = "NetSales"
        case totalTax = "TotalTax"
        case voidedOrdersCount = "VoidedOrdersCount"
        case voidedAmount = "VoidedAmount"
        case totalOrders = "TotalOrders"
        case partialPaymentsCount = "PartialPaymentsCount"
        case partialPaymentsAmount = "PartialPaymentsAmount"
        case refundedOrdersCount = "RefundedOrdersCount"
        case paymentBreakdown = "PaymentBreakdown"
        case cashOpeningBalance = "CashOpeningBalance"
        case cashPayments = "CashPayments"
        case cashRefunds = "CashRefunds"
        case cashClosingBalanceExpected = "CashClosingBalanceExpected"
        case cashClosingBalanceActual = "CashClosingBalanceActual"
        case cashDifference = "CashDifference"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(terminalID, forKey: .terminalID)
        try container.encode(terminalName, forKey: .terminalName)
        try container.encode(sessions, forKey: .sessions)
        try container.encode(grossSales, forKey: .grossSales)
        try container.encode(totalDiscounts, forKey: .totalDiscounts)
        try container.encode(totalRefunds, forKey: .totalRefunds)
        try container.encode(netSales, forKey: .netSales)
        try container.encode(totalTax, forKey: .totalTax)
        try container.encode(voidedOrdersCount, forKey: .voidedOrdersCount)
        try container.encode(voidedAmount, forKey: .voidedAmount)
        try container.encode(totalOrders, forKey: .totalOrders)
        try container.encode(partialPaymentsCount, forKey: .partialPaymentsCount)
        try container.encode(partialPaymentsAmount, forKey: .partialPaymentsAmount)
        try container.encode(refundedOrdersCount, forKey: .refundedOrdersCount)
        try container.encode(paymentBreakdown, forKey: .paymentBreakdown)
        try container.encode(cashOpeningBalance, forKey: .cashOpeningBalance)
        try container.encode(cashPayments, forKey: .cashPayments)
        try container.encode(cashRefunds, forKey: .cashRefunds)
        try container.encode(cashClosingBalanceExpected, forKey: .cashClosingBalanceExpected)
        try container.encode(cashClosingBalanceActual, forKey: .cashClosingBalanceActual)
        try container.encode(cashDifference, forKey: .cashDifference)
    }
}

