//
// TestWebhookResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TestWebhookResponse: Sendable, Codable, Hashable {

    public var message: String
    public var eventType: String
    public var endpointUrl: String
    public var samplePayload: JSONValue?

    public init(message: String, eventType: String, endpointUrl: String, samplePayload: JSONValue?) {
        self.message = message
        self.eventType = eventType
        self.endpointUrl = endpointUrl
        self.samplePayload = samplePayload
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message = "Message"
        case eventType = "EventType"
        case endpointUrl = "EndpointUrl"
        case samplePayload = "SamplePayload"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(message, forKey: .message)
        try container.encode(eventType, forKey: .eventType)
        try container.encode(endpointUrl, forKey: .endpointUrl)
        try container.encode(samplePayload, forKey: .samplePayload)
    }
}

