//
// TransferReason.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum TransferReason: Int, Sendable, Codable, CaseIterable {
    case BranchRequest = 1
    case StockRebalancing = 2
    case StorageRelocation = 3
    case Consolidation = 4
    case RoutineRestocking = 5
    case LowStockAlert = 6
    case StockOut = 7
    case SeasonalDemand = 8
    case CustomerOrder = 9
    case PromotionalCampaign = 10
    case Other = 11
}
