//
// UpdateRefundPolicyRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateRefundPolicyRequest: Sendable, Codable, Hashable {

    public var policyType: RefundDiscountAccountingPolicy
    public var allowFreeItemProportionalRefund: Bool

    public init(policyType: RefundDiscountAccountingPolicy, allowFreeItemProportionalRefund: Bool) {
        self.policyType = policyType
        self.allowFreeItemProportionalRefund = allowFreeItemProportionalRefund
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case policyType = "PolicyType"
        case allowFreeItemProportionalRefund = "AllowFreeItemProportionalRefund"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(policyType, forKey: .policyType)
        try container.encode(allowFreeItemProportionalRefund, forKey: .allowFreeItemProportionalRefund)
    }
}

