//
// UserRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserRequest: Sendable, Codable, Hashable {

    public static let emailRule = StringRule(minLength: 0, maxLength: 100, pattern: "/^[^@]+@[^@]+$/")
    public static let firstNameRule = StringRule(minLength: 0, maxLength: 100, pattern: nil)
    public static let lastNameRule = StringRule(minLength: 0, maxLength: 100, pattern: nil)
    public static let phoneNumberRule = StringRule(minLength: 1, maxLength: nil, pattern: "/^(\\+9665\\d{8}|\\+9715\\d{8}|\\+974[3567]\\d{7}|\\+965[569]\\d{7}|\\+973[36]\\d{7}|\\+9689\\d{7}|\\+9677\\d{7})$/")
    public static let designationRule = StringRule(minLength: 0, maxLength: 100, pattern: nil)
    public static let contactNoRule = StringRule(minLength: 0, maxLength: 20, pattern: nil)
    public static let passwordRule = StringRule(minLength: 8, maxLength: nil, pattern: "/[0-9]/")
    public static let passcodeRule = StringRule(minLength: 4, maxLength: 20, pattern: nil)
    public var email: String
    public var firstName: String?
    public var lastName: String?
    public var phoneNumber: String
    public var designation: String?
    public var contactNo: String?
    public var imagePath: String?
    public var cityID: Int64?
    public var password: String?
    public var statusID: StatusType?
    public var roles: [UserRoleAssignment]?
    public var directPermissions: [UserPermissionAssignment]?
    public var passcode: String?
    /** Account-Location assignments for the user */
    public var accountLocations: [UserAccountLocationAssignment]?

    public init(email: String, firstName: String? = nil, lastName: String? = nil, phoneNumber: String, designation: String? = nil, contactNo: String? = nil, imagePath: String? = nil, cityID: Int64? = nil, password: String? = nil, statusID: StatusType? = nil, roles: [UserRoleAssignment]? = nil, directPermissions: [UserPermissionAssignment]? = nil, passcode: String? = nil, accountLocations: [UserAccountLocationAssignment]? = nil) {
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
        self.phoneNumber = phoneNumber
        self.designation = designation
        self.contactNo = contactNo
        self.imagePath = imagePath
        self.cityID = cityID
        self.password = password
        self.statusID = statusID
        self.roles = roles
        self.directPermissions = directPermissions
        self.passcode = passcode
        self.accountLocations = accountLocations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email = "Email"
        case firstName = "FirstName"
        case lastName = "LastName"
        case phoneNumber = "PhoneNumber"
        case designation = "Designation"
        case contactNo = "ContactNo"
        case imagePath = "ImagePath"
        case cityID = "CityID"
        case password = "Password"
        case statusID = "StatusID"
        case roles = "Roles"
        case directPermissions = "DirectPermissions"
        case passcode = "Passcode"
        case accountLocations = "AccountLocations"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(email, forKey: .email)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encode(phoneNumber, forKey: .phoneNumber)
        try container.encodeIfPresent(designation, forKey: .designation)
        try container.encodeIfPresent(contactNo, forKey: .contactNo)
        try container.encodeIfPresent(imagePath, forKey: .imagePath)
        try container.encodeIfPresent(cityID, forKey: .cityID)
        try container.encodeIfPresent(password, forKey: .password)
        try container.encodeIfPresent(statusID, forKey: .statusID)
        try container.encodeIfPresent(roles, forKey: .roles)
        try container.encodeIfPresent(directPermissions, forKey: .directPermissions)
        try container.encodeIfPresent(passcode, forKey: .passcode)
        try container.encodeIfPresent(accountLocations, forKey: .accountLocations)
    }
}

