//
// UserDetailResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UserDetailResponse: Sendable, Codable, Hashable {

    public var ID: Int64
    public var email: String?
    public var userName: String?
    public var firstName: String?
    public var lastName: String?
    public var fullName: String?
    public var phoneNumber: String?
    public var designation: String?
    public var contactNo: String?
    public var imagePath: String?
    public var cityID: Int64?
    public var cityName: String?
    public var isEmailVerified: Bool
    public var isContactNoVerified: Bool
    public var statusID: StatusType
    public var createdAt: Date?
    public var updatedAt: Date?
    public var userType: String
    public var hasPasscode: Bool
    public var roles: [UserRoleResponse]
    public var permissions: [String]
    public var directPermissions: [PermissionResponse]
    public var accountIDs: [Int64]
    /** Account-Location assignments grouped by account */
    public var accountLocations: [UserAccountLocationResponse]
    public var isLockedOut: Bool
    public var lockoutEnd: Date?
    public var accessFailedCount: Int

    public init(ID: Int64, email: String? = nil, userName: String? = nil, firstName: String? = nil, lastName: String? = nil, fullName: String? = nil, phoneNumber: String? = nil, designation: String? = nil, contactNo: String? = nil, imagePath: String? = nil, cityID: Int64? = nil, cityName: String? = nil, isEmailVerified: Bool, isContactNoVerified: Bool, statusID: StatusType, createdAt: Date? = nil, updatedAt: Date? = nil, userType: String, hasPasscode: Bool, roles: [UserRoleResponse], permissions: [String], directPermissions: [PermissionResponse], accountIDs: [Int64], accountLocations: [UserAccountLocationResponse], isLockedOut: Bool, lockoutEnd: Date? = nil, accessFailedCount: Int) {
        self.ID = ID
        self.email = email
        self.userName = userName
        self.firstName = firstName
        self.lastName = lastName
        self.fullName = fullName
        self.phoneNumber = phoneNumber
        self.designation = designation
        self.contactNo = contactNo
        self.imagePath = imagePath
        self.cityID = cityID
        self.cityName = cityName
        self.isEmailVerified = isEmailVerified
        self.isContactNoVerified = isContactNoVerified
        self.statusID = statusID
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.userType = userType
        self.hasPasscode = hasPasscode
        self.roles = roles
        self.permissions = permissions
        self.directPermissions = directPermissions
        self.accountIDs = accountIDs
        self.accountLocations = accountLocations
        self.isLockedOut = isLockedOut
        self.lockoutEnd = lockoutEnd
        self.accessFailedCount = accessFailedCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ID
        case email = "Email"
        case userName = "UserName"
        case firstName = "FirstName"
        case lastName = "LastName"
        case fullName = "FullName"
        case phoneNumber = "PhoneNumber"
        case designation = "Designation"
        case contactNo = "ContactNo"
        case imagePath = "ImagePath"
        case cityID = "CityID"
        case cityName = "CityName"
        case isEmailVerified = "IsEmailVerified"
        case isContactNoVerified = "IsContactNoVerified"
        case statusID = "StatusID"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case userType = "UserType"
        case hasPasscode = "HasPasscode"
        case roles = "Roles"
        case permissions = "Permissions"
        case directPermissions = "DirectPermissions"
        case accountIDs = "AccountIDs"
        case accountLocations = "AccountLocations"
        case isLockedOut = "IsLockedOut"
        case lockoutEnd = "LockoutEnd"
        case accessFailedCount = "AccessFailedCount"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ID, forKey: .ID)
        try container.encodeIfPresent(email, forKey: .email)
        try container.encodeIfPresent(userName, forKey: .userName)
        try container.encodeIfPresent(firstName, forKey: .firstName)
        try container.encodeIfPresent(lastName, forKey: .lastName)
        try container.encodeIfPresent(fullName, forKey: .fullName)
        try container.encodeIfPresent(phoneNumber, forKey: .phoneNumber)
        try container.encodeIfPresent(designation, forKey: .designation)
        try container.encodeIfPresent(contactNo, forKey: .contactNo)
        try container.encodeIfPresent(imagePath, forKey: .imagePath)
        try container.encodeIfPresent(cityID, forKey: .cityID)
        try container.encodeIfPresent(cityName, forKey: .cityName)
        try container.encode(isEmailVerified, forKey: .isEmailVerified)
        try container.encode(isContactNoVerified, forKey: .isContactNoVerified)
        try container.encode(statusID, forKey: .statusID)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encode(userType, forKey: .userType)
        try container.encode(hasPasscode, forKey: .hasPasscode)
        try container.encode(roles, forKey: .roles)
        try container.encode(permissions, forKey: .permissions)
        try container.encode(directPermissions, forKey: .directPermissions)
        try container.encode(accountIDs, forKey: .accountIDs)
        try container.encode(accountLocations, forKey: .accountLocations)
        try container.encode(isLockedOut, forKey: .isLockedOut)
        try container.encodeIfPresent(lockoutEnd, forKey: .lockoutEnd)
        try container.encode(accessFailedCount, forKey: .accessFailedCount)
    }
}

