//
// WarehouseStockResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct WarehouseStockResponse: Sendable, Codable, Hashable {

    public var stockID: Int64
    public var warehouseID: Int64
    public var openingStock: Double
    public var currentStock: Double
    public var minimumStockToReorder: Double
    public var createdAt: Date?
    public var updatedAt: Date?
    public var statusID: StatusType

    public init(stockID: Int64, warehouseID: Int64, openingStock: Double, currentStock: Double, minimumStockToReorder: Double, createdAt: Date? = nil, updatedAt: Date? = nil, statusID: StatusType) {
        self.stockID = stockID
        self.warehouseID = warehouseID
        self.openingStock = openingStock
        self.currentStock = currentStock
        self.minimumStockToReorder = minimumStockToReorder
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.statusID = statusID
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case stockID = "StockID"
        case warehouseID = "WarehouseID"
        case openingStock = "OpeningStock"
        case currentStock = "CurrentStock"
        case minimumStockToReorder = "MinimumStockToReorder"
        case createdAt = "CreatedAt"
        case updatedAt = "UpdatedAt"
        case statusID = "StatusID"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(stockID, forKey: .stockID)
        try container.encode(warehouseID, forKey: .warehouseID)
        try container.encode(openingStock, forKey: .openingStock)
        try container.encode(currentStock, forKey: .currentStock)
        try container.encode(minimumStockToReorder, forKey: .minimumStockToReorder)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(updatedAt, forKey: .updatedAt)
        try container.encode(statusID, forKey: .statusID)
    }
}

