//
// ZReportRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Request to generate a Z Report (end-of-day summary) for a location */
public struct ZReportRequest: Sendable, Codable, Hashable {

    /** The date to generate the Z Report for */
    public var date: Date

    public init(date: Date) {
        self.date = date
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date = "Date"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(date, forKey: .date)
    }
}

